package chat.oldy;

import android.os.Build;
import android.widget.*;
import org.json.*;

final class AccountDevices {
 static void show(MainActivity a){LinearLayout b=PersonalHub.page(a,"Устройства и сессии");TextView state=a.label("Проверяем активные сессии…",14,a.MUTED);b.addView(state);final Vault owner=a.vault;a.work.execute(()->{try{JSONObject response=a.api.call("/sessions",new JSONObject().put("device",Build.MANUFACTURER+" "+Build.MODEL).put("platform","Android "+Build.VERSION.RELEASE),owner.token());JSONArray items=response.getJSONArray("items");a.runOnUiThread(()->{if(a.isDestroyed()||a.vault!=owner)return;b.removeAllViews();for(int n=0;n<items.length();n++){JSONObject item=items.optJSONObject(n);if(item==null)continue;boolean current=item.optBoolean("current");String label=item.optString("device","Устройство")+(current?" · Это устройство":"");SettingsHome.row(a,b,"▣",label,item.optLong("last_seen")>0?"Активность: "+PersonalReminders.format(item.optLong("last_seen")*1000):"Время последней активности неизвестно",0xff6989db,()->{if(current)a.dialog().setTitle("Выйти на этом устройстве?").setPositiveButton("Выйти",(d,w)->a.task(()->{a.api.call("/sessions/revoke",new JSONObject().put("id",item.getString("id")),owner.token());a.runOnUiThread(a::logoutAccount);})).setNegativeButton("Отмена",null).show();else a.dialog().setTitle("Завершить эту сессию?").setPositiveButton("Завершить",(d,w)->a.task(()->{a.api.call("/sessions/revoke",new JSONObject().put("id",item.getString("id")),owner.token());a.runOnUiThread(()->show(a));})).setNegativeButton("Отмена",null).show();});}});}catch(Exception e){a.runOnUiThread(()->{if(a.isDestroyed()||a.vault!=owner)return;state.setText(e instanceof Api.Failure&&((Api.Failure)e).status==404?"Это устройство: "+Build.MANUFACTURER+" "+Build.MODEL+"\nСписок остальных сессий требует обновления сервера чата.":"Не удалось получить список сессий. Проверьте подключение.");b.addView(a.button("Повторить",false,()->show(a)));});}});}
}
