package chat.oldy;

import android.app.*;import android.content.*;import android.media.AudioManager;import android.os.*;
import org.json.*;import org.webrtc.*;import java.util.*;import java.util.concurrent.*;

/** Up to five devices, pairwise DTLS-SRTP, authenticated private-message signalling.
 * The inviter controls the consented roster. A relay forwards encrypted packets only. */
final class ConferenceCall {
 static volatile Session current;
 static final Set<String> ended=Collections.newSetFromMap(new ConcurrentHashMap<String,Boolean>());
 static synchronized void dial(Context c,List<String> peers)throws Exception{
  if(current!=null){c.startActivity(new Intent(c,VideoCallActivity.class).addFlags(Intent.FLAG_ACTIVITY_NEW_TASK));return;}
  if(LiveCall.current!=null)throw new Exception("Сначала завершите текущий звонок");Vault v=ChatService.vault(c);LinkedHashSet<String> members=new LinkedHashSet<>();members.add(v.nick());for(String peer:peers){if(!peer.matches("[a-z0-9_]{3,24}")||v.isBlocked(peer))throw new Exception("Участник недоступен");members.add(peer);}if(members.size()<2||members.size()>5)throw new Exception("Выберите от 1 до 4 собеседников");current=new Session(c,v,UUID.randomUUID().toString(),v.nick(),members,false);c.startActivity(new Intent(c,VideoCallActivity.class).addFlags(Intent.FLAG_ACTIVITY_NEW_TASK));
 }
 static synchronized void receive(ChatService service,String from,JSONObject p){
  if(service.vault!=ChatService.shared||!service.running||service.vault.isBlocked(from))return;String id=p.optString("cid"),op=p.optString("op");if(!id.matches("[a-f0-9-]{36}")||ended.contains(id)||Math.abs(System.currentTimeMillis()-p.optLong("sent_at"))>90000)return;
  try{if(op.equals("vc_invite")){if(!from.equals(p.optString("host")))return;LinkedHashSet<String> members=members(p.getJSONArray("members"));if(!members.contains(from)||!members.contains(service.vault.nick()))return;if(current!=null||LiveCall.current!=null){if(current==null||!current.id.equals(id))signal(service.vault,from,new JSONObject().put("op","vc_busy").put("cid",id));return;}Session s=new Session(service,service.vault,id,from,members,true);current=s;s.notice();s.timer.schedule(()->{if(!s.accepted)s.end("Пропущенный видеозвонок",true);},55,TimeUnit.SECONDS);return;}
   Session s=current;if(s==null||!s.id.equals(id)||!s.invited.contains(from))return;s.execute(()->s.handle(from,p));
  }catch(Exception ignored){}
 }
 static LinkedHashSet<String> members(JSONArray a)throws Exception{if(a.length()<2||a.length()>5)throw new Exception();LinkedHashSet<String> result=new LinkedHashSet<>();for(int i=0;i<a.length();i++){String n=a.getString(i);if(!n.matches("[a-z0-9_]{3,24}")||!result.add(n))throw new Exception();}return result;}
 static void signal(Vault owner,String peer,JSONObject p){try{ChatService s=ChatService.instance;if(s!=null&&s.running&&s.vault==owner)s.signal(peer,p.put("sent_at",System.currentTimeMillis()));}catch(Exception ignored){}}
 static final class Sink implements VideoSink {volatile VideoSink target;public void onFrame(VideoFrame frame){VideoSink view=target;if(view!=null)view.onFrame(frame);}}
 static final class Session {
  final Context c;final Vault vault;final String id,host;final Set<String> invited;final boolean incoming;
  final ExecutorService io=Executors.newSingleThreadExecutor();final ScheduledExecutorService timer=Executors.newSingleThreadScheduledExecutor();
  final Map<String,Link> links=new LinkedHashMap<>();final Set<String> joined=new LinkedHashSet<>();final Map<String,JSONObject> waitingOffers=new HashMap<>();
  final ConcurrentHashMap<String,Sink> pictures=new ConcurrentHashMap<>();final ConcurrentHashMap<String,String> states=new ConcurrentHashMap<>();final Sink local=new Sink();
  volatile boolean accepted,ready,closed,muted,cameraOff;volatile String state;volatile long connectedAt;volatile int rosterVersion;int acceptedVersion=-1;
  EglBase egl;PeerConnectionFactory factory;AudioSource audioSource;org.webrtc.AudioTrack audio;VideoSource videoSource;VideoTrack video;VideoCapturer camera;SurfaceTextureHelper texture;volatile boolean captureRunning;
  Session(Context c,Vault v,String id,String host,Set<String> members,boolean incoming){this.c=c.getApplicationContext();vault=v;this.id=id;this.host=host;invited=Collections.unmodifiableSet(new LinkedHashSet<>(members));this.incoming=incoming;state=incoming?"Входящий видеозвонок":"Подготавливаем звонок…";for(String n:members)if(!n.equals(v.nick()))states.put(n,"Приглашение");}
  void execute(Runnable r){if(!closed)try{io.execute(()->{if(!closed)try{r.run();}catch(Exception e){end("Не удалось продолжить звонок",true);}});}catch(RejectedExecutionException ignored){}}
  synchronized void start(){if(closed||accepted)return;if(ChatService.instance==null||ChatService.instance.vault!=vault){end("Откройте чат и повторите звонок",true);return;}accepted=true;c.getSystemService(NotificationManager.class).cancel(420);try{ChatService.instance.callForeground(true,"Видеосвязь");}catch(Exception e){end("Разрешите доступ к камере и микрофону",true);return;}
   execute(()->{try{PeerConnectionFactory.initialize(PeerConnectionFactory.InitializationOptions.builder(c).createInitializationOptions());egl=EglBase.create();factory=PeerConnectionFactory.builder().setVideoEncoderFactory(new DefaultVideoEncoderFactory(egl.getEglBaseContext(),true,true)).setVideoDecoderFactory(new DefaultVideoDecoderFactory(egl.getEglBaseContext())).createPeerConnectionFactory();MediaConstraints constraints=new MediaConstraints();constraints.mandatory.add(new MediaConstraints.KeyValuePair("googEchoCancellation","true"));constraints.mandatory.add(new MediaConstraints.KeyValuePair("googNoiseSuppression","true"));audioSource=factory.createAudioSource(constraints);audio=factory.createAudioTrack("oldi-audio",audioSource);audio.setEnabled(!muted);
    CameraEnumerator enumerator=Camera2Enumerator.isSupported(c)?new Camera2Enumerator(c):new Camera1Enumerator(true);String device=null;for(String name:enumerator.getDeviceNames())if(enumerator.isFrontFacing(name)){device=name;break;}if(device==null&&enumerator.getDeviceNames().length>0)device=enumerator.getDeviceNames()[0];if(device==null)throw new Exception("Нет камеры");camera=enumerator.createCapturer(device,null);if(camera==null)throw new Exception("Камера недоступна");videoSource=factory.createVideoSource(false);texture=SurfaceTextureHelper.create("oldi-camera",egl.getEglBaseContext());camera.initialize(texture,c,videoSource.getCapturerObserver());video=factory.createVideoTrack("oldi-video",videoSource);video.addSink(local);capture();AudioManager sound=c.getSystemService(AudioManager.class);sound.setMode(AudioManager.MODE_IN_COMMUNICATION);sound.setSpeakerphoneOn(true);ready=true;state="Ожидаем участников…";
    if(host.equals(vault.nick())){joined.add(host);for(String n:invited)if(!n.equals(host))send(n,"vc_invite",new JSONObject().put("host",host).put("members",new JSONArray(invited)));}else send(host,"vc_join",new JSONObject());
    timer.schedule(()->execute(()->{if(connectedAt==0)end("Нет ответа от участников",true);}),80,TimeUnit.SECONDS);ChatService.changed(c);
   }catch(Exception e){end("Не удалось включить камеру или микрофон",true);}});
  }
  void capture()throws Exception{if(camera==null||captureRunning||cameraOff)return;int width=invited.size()>2?480:640,height=invited.size()>2?360:480;camera.startCapture(width,height,20);captureRunning=true;}
  void send(String peer,String op,JSONObject p){try{signal(vault,peer,p.put("op",op).put("cid",id));}catch(Exception ignored){}}
  void handle(String from,JSONObject p){try{String op=p.optString("op");
   if(op.equals("vc_end")&&from.equals(host)){end("Видеозвонок завершён",false);return;}
   if(op.equals("vc_leave")||op.equals("vc_busy")){states.put(from,op.equals("vc_busy")?"Занят":"Вышел из звонка");if(host.equals(vault.nick())&&joined.remove(from))broadcastRoster();Link old=links.remove(from);if(old!=null)old.close();return;}
   if(!ready)return;
   if(op.equals("vc_join")&&host.equals(vault.nick())){if(joined.add(from))broadcastRoster();else sendRoster(from);return;}
   if(op.equals("vc_roster")&&from.equals(host)){JSONArray a=p.getJSONArray("members");LinkedHashSet<String> next=members(a);int version=p.getInt("revision");if(version<=acceptedVersion||!invited.containsAll(next)||!next.contains(vault.nick())||!next.contains(host))return;acceptedVersion=version;setRoster(next);return;}
   if(op.equals("vc_offer")&&!joined.contains(from)){if(waitingOffers.size()<4)waitingOffers.put(from,new JSONObject(p.toString()));return;}
   if(!joined.contains(from)||from.equals(vault.nick()))return;Link link=links.get(from);
   if(op.equals("vc_offer")){if(from.compareTo(vault.nick())>=0||link==null||link.pc.getRemoteDescription()!=null)return;String sdp=p.optString("sdp");if(sdp.length()>14000)return;link.pc.setRemoteDescription(link.observer(()->{link.flushIce();link.pc.createAnswer(link.description(),new MediaConstraints());}),new SessionDescription(SessionDescription.Type.OFFER,sdp));}
   if(op.equals("vc_answer")&&link!=null&&vault.nick().compareTo(from)<0&&link.pc.getRemoteDescription()==null){String sdp=p.optString("sdp");if(sdp.length()>14000)return;link.pc.setRemoteDescription(link.observer(link::flushIce),new SessionDescription(SessionDescription.Type.ANSWER,sdp));}
   if(op.equals("vc_ice")&&link!=null){String candidate=p.optString("candidate");int index=p.optInt("line",-1);if(candidate.length()>1500||index<0||index>8)return;IceCandidate ice=new IceCandidate(p.optString("mid"),index,candidate);if(link.pc.getRemoteDescription()==null){if(link.ice.size()<24)link.ice.add(ice);}else link.pc.addIceCandidate(ice);}
  }catch(Exception bad){states.put(from,"Не удалось соединиться");}}
  void sendRoster(String peer)throws Exception{send(peer,"vc_roster",new JSONObject().put("members",new JSONArray(joined)).put("revision",rosterVersion));}
  void broadcastRoster()throws Exception{rosterVersion++;for(String n:joined)if(!n.equals(vault.nick()))sendRoster(n);setRoster(new LinkedHashSet<>(joined));}
  void setRoster(Set<String> members)throws Exception{joined.clear();joined.addAll(members);for(String n:new ArrayList<>(links.keySet()))if(!members.contains(n)){links.remove(n).close();states.put(n,"Вышел из звонка");}
   for(String n:members)if(!n.equals(vault.nick())&&!links.containsKey(n)){if(vault.isBlocked(n))continue;Link link=new Link(n);links.put(n,link);link.create();JSONObject pending=waitingOffers.remove(n);if(pending!=null)handle(n,pending);}
  }
  void mute(){muted=!muted;execute(()->{if(audio!=null)audio.setEnabled(!muted);});}
  void camera(){cameraOff=!cameraOff;execute(()->{try{video.setEnabled(!cameraOff);if(cameraOff&&captureRunning){camera.stopCapture();captureRunning=false;}else capture();}catch(Exception e){state="Не удалось переключить камеру";}});}
  void flip(){execute(()->{if(camera instanceof CameraVideoCapturer)((CameraVideoCapturer)camera).switchCamera(null);});}
  void notice(){NotificationManager nm=c.getSystemService(NotificationManager.class);NotificationChannel ch=new NotificationChannel("video_calls","Видеозвонки",NotificationManager.IMPORTANCE_HIGH);ch.setSound(android.provider.Settings.System.DEFAULT_RINGTONE_URI,new android.media.AudioAttributes.Builder().setUsage(android.media.AudioAttributes.USAGE_NOTIFICATION_RINGTONE).build());ch.enableVibration(true);nm.createNotificationChannel(ch);Intent open=new Intent(c,VideoCallActivity.class).putExtra("cid",id).addFlags(Intent.FLAG_ACTIVITY_NEW_TASK|Intent.FLAG_ACTIVITY_CLEAR_TOP);PendingIntent view=PendingIntent.getActivity(c,420,open,PendingIntent.FLAG_IMMUTABLE|PendingIntent.FLAG_UPDATE_CURRENT);PendingIntent accept=PendingIntent.getActivity(c,421,new Intent(open).putExtra("accept",true),PendingIntent.FLAG_IMMUTABLE|PendingIntent.FLAG_UPDATE_CURRENT);PendingIntent reject=PendingIntent.getBroadcast(c,422,new Intent(c,CallActionReceiver.class).putExtra("cid",id),PendingIntent.FLAG_IMMUTABLE|PendingIntent.FLAG_UPDATE_CURRENT);nm.notify(420,new Notification.Builder(c,"video_calls").setSmallIcon(R.drawable.ic_launcher).setContentTitle("Видеозвонок от @"+host).setContentText("Участников: "+invited.size()).setCategory(Notification.CATEGORY_CALL).setContentIntent(view).setOngoing(true).addAction(new Notification.Action.Builder(null,"Ответить",accept).build()).addAction(new Notification.Action.Builder(null,"Отклонить",reject).build()).build());ChatService.changed(c);}
  synchronized void end(String reason,boolean notify){if(closed)return;closed=true;state=reason;if(notify){if(host.equals(vault.nick()))for(String n:invited){if(!n.equals(host))send(n,"vc_end",new JSONObject());}else send(host,"vc_leave",new JSONObject());}ended.add(id);if(ended.size()>100)ended.clear();timer.shutdownNow();c.getSystemService(NotificationManager.class).cancel(420);new Handler(Looper.getMainLooper()).post(()->{VideoCallActivity.detach(this);io.execute(()->{try{for(Link l:links.values())l.close();if(camera!=null){if(captureRunning)try{camera.stopCapture();}catch(InterruptedException ignored){}camera.dispose();}if(video!=null){video.removeSink(local);video.dispose();}if(videoSource!=null)videoSource.dispose();if(texture!=null)texture.dispose();if(audio!=null)audio.dispose();if(audioSource!=null)audioSource.dispose();if(factory!=null)factory.dispose();if(egl!=null)egl.release();}finally{AudioManager sound=c.getSystemService(AudioManager.class);sound.setSpeakerphoneOn(false);sound.setMode(AudioManager.MODE_NORMAL);if(current==this)current=null;ChatService s=ChatService.instance;if(s!=null&&s.vault==vault)s.callForeground(false,"");ChatService.changed(c);}});io.shutdown();});}
  final class Link {
   final String peer;PeerConnection pc;boolean sent,initiator;int iceSent;final List<IceCandidate> ice=new ArrayList<>();
   Link(String n){peer=n;initiator=vault.nick().compareTo(n)<0;}
   void create()throws Exception{JSONObject config=new Api(c).call("/call-config",new JSONObject().put("peer",peer),vault.token());List<PeerConnection.IceServer> servers=new ArrayList<>();JSONArray all=config.getJSONArray("servers");for(int i=0;i<all.length();i++){JSONObject server=all.getJSONObject(i);PeerConnection.IceServer.Builder builder=PeerConnection.IceServer.builder(server.getString("url"));if(server.has("username"))builder.setUsername(server.getString("username")).setPassword(server.getString("credential"));servers.add(builder.createIceServer());}PeerConnection.RTCConfiguration rtc=new PeerConnection.RTCConfiguration(servers);rtc.sdpSemantics=PeerConnection.SdpSemantics.UNIFIED_PLAN;rtc.bundlePolicy=PeerConnection.BundlePolicy.MAXBUNDLE;if(config.optBoolean("relay_only"))rtc.iceTransportsType=PeerConnection.IceTransportsType.RELAY;
    pc=factory.createPeerConnection(rtc,new PeerConnection.Observer(){public void onSignalingChange(PeerConnection.SignalingState s){}public void onIceConnectionReceivingChange(boolean b){}public void onIceGatheringChange(PeerConnection.IceGatheringState s){if(s==PeerConnection.IceGatheringState.COMPLETE)execute(()->sendSdp());}public void onIceCandidatesRemoved(IceCandidate[] candidates){}public void onRemoveStream(MediaStream stream){}public void onRenegotiationNeeded(){}public void onDataChannel(DataChannel channel){channel.close();}
     public void onIceConnectionChange(PeerConnection.IceConnectionState s){if(closed)return;execute(()->{if(s==PeerConnection.IceConnectionState.CONNECTED||s==PeerConnection.IceConnectionState.COMPLETED){states.put(peer,"На связи");state="На связи";if(connectedAt==0)connectedAt=SystemClock.elapsedRealtime();}else if(s==PeerConnection.IceConnectionState.FAILED)states.put(peer,"Соединение прервалось");else if(s==PeerConnection.IceConnectionState.DISCONNECTED)states.put(peer,"Восстанавливаем связь…");});}
     public void onIceCandidate(IceCandidate candidate){execute(()->{if(sent&&iceSent++<24)try{send(peer,"vc_ice",new JSONObject().put("candidate",candidate.sdp).put("mid",candidate.sdpMid).put("line",candidate.sdpMLineIndex));}catch(Exception ignored){}});}
     public void onAddStream(MediaStream stream){for(VideoTrack track:stream.videoTracks)track(track);for(org.webrtc.AudioTrack track:stream.audioTracks)track.setEnabled(true);}
     public void onAddTrack(RtpReceiver receiver,MediaStream[] streams){if(receiver.track() instanceof VideoTrack)track((VideoTrack)receiver.track());if(receiver.track() instanceof org.webrtc.AudioTrack)receiver.track().setEnabled(true);}
     void track(VideoTrack track){execute(()->{Sink sink=pictures.computeIfAbsent(peer,n->new Sink());track.addSink(sink);});}
    });if(pc==null)throw new Exception("WebRTC недоступен");pc.addTrack(audio,Collections.singletonList("oldi-conference"));RtpSender sender=pc.addTrack(video,Collections.singletonList("oldi-conference"));RtpParameters params=sender.getParameters();for(RtpParameters.Encoding encoding:params.encodings){encoding.maxBitrateBps=invited.size()>2?280000:750000;encoding.maxFramerate=20;}sender.setParameters(params);states.put(peer,"Соединяем…");if(initiator)pc.createOffer(description(),new MediaConstraints());
   }
   SdpObserver observer(Runnable success){return new SdpObserver(){public void onSetSuccess(){execute(success);}public void onSetFailure(String e){states.put(peer,"Ошибка соединения");}public void onCreateSuccess(SessionDescription s){}public void onCreateFailure(String e){states.put(peer,"Ошибка соединения");}};}
   SdpObserver description(){return new SdpObserver(){public void onCreateSuccess(SessionDescription s){execute(()->pc.setLocalDescription(observer(()->timer.schedule(()->execute(()->sendSdp()),4,TimeUnit.SECONDS)),s));}public void onSetSuccess(){}public void onSetFailure(String e){states.put(peer,"Ошибка соединения");}public void onCreateFailure(String e){states.put(peer,"Ошибка соединения");}};}
   void sendSdp(){if(sent||closed||pc==null||pc.getLocalDescription()==null)return;String sdp=pc.getLocalDescription().description;if(sdp.length()>14000){states.put(peer,"Не удалось согласовать связь");return;}try{sent=true;send(peer,initiator?"vc_offer":"vc_answer",new JSONObject().put("sdp",sdp));}catch(Exception ignored){}}
   void flushIce(){for(IceCandidate candidate:ice)pc.addIceCandidate(candidate);ice.clear();}
   void close(){Sink sink=pictures.remove(peer);if(sink!=null)sink.target=null;if(pc!=null){pc.close();pc.dispose();pc=null;}}
  }
 }
}
