package chat.oldy;
import android.widget.*;import org.json.*;import java.util.*;

/** Only messages explicitly configured by their author can enter the deletion queue. */
final class EventExpiry {
 static boolean event(String value){return value.equals("read")||value.equals("reply")||value.equals("open");}
 static void choose(MainActivity a,JSONObject m){if(!m.optBoolean("out")||Conversation.community(m.optString("peer")))return;try{JSONObject peer=a.vault.peer(m.optString("peer"));if(peer==null||peer.optInt("protocol")<5){a.error("Для удаления по событию обновите Oldi на обоих устройствах.");return;}LinearLayout b=a.col();String[] events=m.optString("kind").equals("file")?new String[]{"open",""}:new String[]{"read","reply",""};for(String value:events)b.addView(a.button(value.equals("read")?"После прочтения":value.equals("reply")?"После ответа":value.equals("open")?"После открытия файла":"Оставлять сообщение",false,()->{try{ChatSharing.send(a,m.optString("peer"),new JSONObject().put("kind","control").put("op","expire_config").put("mid",m.optString("id")).put("event",value).put("config",UUID.randomUUID().toString()));}catch(Exception e){a.error(Api.message(e));}}));a.sheet("Удаление по событию",b);}catch(Exception e){a.error(Api.message(e));}}
 static void configure(Vault v,JSONObject target,String sender,JSONObject control,long time)throws Exception{String value=control.optString("event");if(!value.isEmpty()&&!event(value))throw new IllegalArgumentException("Expiry event");if(!control.optString("config").matches("[a-f0-9-]{36}")||target==null||Conversation.community(target.optString("peer")))throw new IllegalArgumentException("Expiry target");String author=target.optBoolean("out")?v.nick():target.optString("from");if(!author.equals(sender))throw new SecurityException("Only the author can configure expiry");if(time<target.optLong("expiry_config_at"))return;JSONArray all=v.data.getJSONArray("messages");for(int n=0;n<all.length();n++){JSONObject m=all.getJSONObject(n);if(m.optString("id").equals(target.optString("id")))m.put("expire_event",value).put("expiry_config_at",time).put("expiry_config_id",control.optString("config"));}v.bucket("event_deletions").remove(target.optString("id"));}
 static void receipt(Vault v,JSONObject target,String sender,JSONObject control)throws Exception{if(sender.equals(v.nick()))return;if(target==null||!target.optBoolean("out")||Conversation.community(target.optString("peer"))||!target.optString("peer").equals(sender))throw new SecurityException("Invalid expiry receipt");String event=control.optString("event");if(!event(event)||!target.optString("expire_event").equals(event)||!target.optString("expiry_config_id").equals(control.optString("config")))return;v.bucket("event_deletions").put(target.getString("id"),target.optString("expiry_config_id"));}
 static void notify(MainActivity a,JSONObject message,String event){notify(a.vault,message,event,a.work);}
 static void notify(Vault owner,JSONObject message,String event,java.util.concurrent.Executor worker){if(message.optBoolean("out")||Conversation.community(message.optString("peer"))||!event.equals(message.optString("expire_event")))return;worker.execute(()->{try{synchronized(owner){JSONObject current=owner.message(message.getString("id"));if(current==null||!event.equals(current.optString("expire_event")))return;String key=current.getString("id")+":"+current.optLong("expiry_config_at");if(owner.bucket("expiry_receipts_sent").has(key))return;owner.queuePayload(current.getString("peer"),new JSONObject().put("kind","control").put("op","expire_event").put("mid",current.getString("id")).put("event",event).put("config",current.optString("expiry_config_id")),null);owner.bucket("expiry_receipts_sent").put(key,true);owner.save();}}catch(Exception ignored){}});}
 static boolean render(MainActivity a,LinearLayout b,JSONObject m){String rule=m.optString("expire_event");if(!event(rule))return false;b.addView(a.label(rule.equals("read")?"Исчезнет после прочтения":rule.equals("reply")?"Исчезнет после ответа":"Исчезнет после открытия",11,a.MUTED));if(rule.equals("read")&&!m.optBoolean("out")&&m.optString("kind").equals("text")){b.addView(a.button("Прочитать сообщение",true,()->{TextView text=a.label(m.optString("text"),17,a.TEXT);a.pad(text,16);ScrollView scroll=new ScrollView(a);scroll.addView(text);a.dialog().setTitle("Сообщение").setView(scroll).setPositiveButton("Прочитано",(d,w)->notify(a,m,"read")).show();}));return true;}return false;}
 static void receivedReply(Vault v,JSONObject received)throws Exception{JSONObject reply=received.optJSONObject("reply");if(reply==null||received.optBoolean("out"))return;JSONObject original=v.message(reply.optString("id"));if(original!=null&&original.optBoolean("out")&&original.optString("expire_event").equals("reply")&&!Conversation.community(original.optString("peer"))&&original.optString("peer").equals(received.optString("from")))v.bucket("event_deletions").put(original.getString("id"),original.optString("expiry_config_id"));}
 static void drain(ChatService service){try{List<String> ids=new ArrayList<>();synchronized(service.vault){service.vault.bucket("event_deletions").keys().forEachRemaining(ids::add);}int count=0;for(String id:ids){if(++count>5||!service.running)return;JSONObject m=service.vault.message(id);if(m==null){synchronized(service.vault){service.vault.bucket("event_deletions").remove(id);service.vault.save();}continue;}if(!m.optBoolean("out")||!event(m.optString("expire_event"))||Conversation.community(m.optString("peer")))continue;ChatService.register(service.api,service.vault,m);synchronized(service.vault){JSONObject latest=service.vault.message(id);if(latest==null||!latest.optString("expiry_config_id").equals(service.vault.bucket("event_deletions").optString(id))||!event(latest.optString("expire_event")))continue;}JSONObject result=service.api.call("/posts/delete",new JSONObject().put("mid",id).put("room",""),service.vault.token());synchronized(service.vault){service.vault.deletion(result);service.vault.bucket("event_deletions").remove(id);service.vault.save();}ChatService.changed(service);}}catch(Exception pending){/* Retry later; never delete locally before the server confirms it. */}}
}
