package chat.oldy;
import android.view.*;import android.widget.*;import org.json.JSONObject;import java.util.*;

/** Selection belongs to the current activity/account; message content is sent only on an explicit AI action. */
final class MessageSelection {
 static final WeakHashMap<MainActivity,LinkedHashMap<String,JSONObject>> selections=new WeakHashMap<>();
 static LinkedHashMap<String,JSONObject> selected(MainActivity a){return selections.computeIfAbsent(a,key->new LinkedHashMap<>());}
 static void bind(MainActivity a,View view,JSONObject message){if(message.optString("id").equals(view.getTag()))view.setAlpha(selected(a).containsKey(message.optString("id"))?.72f:1);view.setOnLongClickListener(v->{v.performHapticFeedback(HapticFeedbackConstants.LONG_PRESS);show(a,message);return true;});if(view instanceof ViewGroup){ViewGroup g=(ViewGroup)view;for(int i=0;i<g.getChildCount();i++)bind(a,g.getChildAt(i),message);}}
 static void clear(MainActivity a){for(String id:selected(a).keySet())if(a.content!=null){View bubble=a.content.findViewWithTag(id);if(bubble!=null)bubble.setAlpha(1);}selections.remove(a);a.selectedMessage=null;if(a.selectionBar!=null&&a.selectionBar.getParent() instanceof ViewGroup)((ViewGroup)a.selectionBar.getParent()).removeView(a.selectionBar);if(a.selectionHeader!=null)a.selectionHeader.setVisibility(View.VISIBLE);a.selectionBar=null;a.selectionHeader=null;}
 static void show(MainActivity a,JSONObject message){if(!a.screen.equals("chat"))return;LinkedHashMap<String,JSONObject> picked=selected(a);String id=message.optString("id");if(picked.containsKey(id))picked.remove(id);else{if(picked.size()>=30){Toast.makeText(a,"Можно выделить до 30 сообщений",Toast.LENGTH_SHORT).show();return;}picked.put(id,message);}if(a.content!=null){View bubble=a.content.findViewWithTag(id);if(bubble!=null)bubble.setAlpha(picked.containsKey(id)?.72f:1);}if(picked.isEmpty()){clear(a);return;}a.selectedMessage=picked.values().iterator().next();if(a.selectionHeader==null)a.selectionHeader=a.root.getChildAt(0);if(a.selectionHeader!=null)a.selectionHeader.setVisibility(View.GONE);if(a.selectionBar!=null&&a.selectionBar.getParent() instanceof ViewGroup)((ViewGroup)a.selectionBar.getParent()).removeView(a.selectionBar);
  LinearLayout bar=a.row();a.selectionBar=bar;bar.setGravity(Gravity.CENTER_VERTICAL);bar.setBackground(a.glass(24));a.pad(bar,4);bar.addView(key(a,"close","Отмена",()->clear(a)),new LinearLayout.LayoutParams(a.dp(42),a.dp(48)));TextView count=a.label("Выбрано "+picked.size(),14,a.TEXT);count.setTypeface(null,android.graphics.Typeface.BOLD);count.setSingleLine(true);count.setEllipsize(android.text.TextUtils.TruncateAt.END);bar.addView(count,new LinearLayout.LayoutParams(0,-2,1));List<JSONObject> items=new ArrayList<>(picked.values());items.sort(Comparator.comparingLong(m->m.optLong("time")));JSONObject first=items.get(0);
  if(items.size()==1)bar.addView(key(a,"reply","Ответить",()->{clear(a);if(a.compose!=null){a.replyTo=first;a.renderReply();a.compose.requestFocus();}}),new LinearLayout.LayoutParams(a.dp(42),a.dp(48)));
  bar.addView(key(a,"copy","Копировать",()->{StringBuilder text=new StringBuilder();for(JSONObject item:items){if(text.length()>0)text.append("\n\n");text.append(Payload.preview(item));}clear(a);a.getSystemService(android.content.ClipboardManager.class).setPrimaryClip(android.content.ClipData.newPlainText("Oldi",text.toString()));}),new LinearLayout.LayoutParams(a.dp(42),a.dp(48)));
  bar.addView(key(a,"sparkles","AI для фрагмента",()->{clear(a);SelectedAssistant.show(a,items);}),new LinearLayout.LayoutParams(a.dp(42),a.dp(48)));
  if(items.size()==1){bar.addView(key(a,"more","Действия",()->{clear(a);a.messageMenu(first);}),new LinearLayout.LayoutParams(a.dp(42),a.dp(48)));try{if(first.optBoolean("out")||a.vault.moderator()||!Conversation.community(a.chat))bar.addView(key(a,"delete","Удалить",()->{clear(a);a.deletePost(first);}),new LinearLayout.LayoutParams(a.dp(42),a.dp(48)));}catch(Exception ignored){}}
  a.root.addView(bar,0,new LinearLayout.LayoutParams(-1,a.dp(68)));
 }
 static View key(MainActivity a,String icon,String label,Runnable action){UiIcon v=new UiIcon(a,icon,a.TEXT);v.setContentDescription(I18n.t(label));v.setOnClickListener(w->action.run());v.setOnLongClickListener(w->{Toast.makeText(a,I18n.t(label),Toast.LENGTH_SHORT).show();return true;});return v;}
}
