package chat.oldy;

import android.graphics.*;
import android.view.*;
import android.widget.*;
import org.json.*;
import java.security.SecureRandom;
import java.util.*;

/** Shared tools use ordinary encrypted messages with readable text for older clients. */
final class MiniTools {
 static final SecureRandom RANDOM=new SecureRandom();
 static String title(String type){return type.equals("poll")?"Опрос":type.equals("list")?"Совместный список":type.equals("timer")?"Таймер":type.equals("wheel")?"Колесо выбора":"Жеребьёвка";}
 static boolean valid(JSONObject tool){if(tool==null||!tool.optString("id").matches("[a-f0-9-]{36}")||!tool.optString("type").matches("poll|list|timer|wheel|draw")||tool.optString("title").length()>200)return false;JSONArray values=tool.optJSONArray("items");return tool.optString("type").equals("timer")?tool.optLong("until")>0:values!=null&&values.length()>=2&&values.length()<=20&&values.toString().length()<=4000;}
 static void choose(MainActivity a){LinearLayout b=a.col();for(String type:new String[]{"poll","list","wheel","draw","timer"}){b.addView(a.button(title(type),false,()->create(a,type)));a.space(b,6);}a.sheet("Вместе в чате",b);}
 static void create(MainActivity a,String type){LinearLayout b=a.col();EditText name=a.field(b,"Название",false);name.setText(title(type));EditText values=a.field(b,type.equals("timer")?"Минуты, от 1 до 1440":"Варианты, каждый с новой строки",false);values.setSingleLine(false);values.setMinLines(type.equals("timer")?1:4);if(type.equals("timer")){values.setInputType(2);values.setText("5");}final String chat=a.screen.equals("chat")?a.chat:"";TextView send=a.button(chat.isEmpty()?"Выбрать чат":"Отправить в этот чат",true,()->{});b.addView(send);send.setOnClickListener(v->{try{JSONObject mini=new JSONObject().put("id",UUID.randomUUID().toString()).put("type",type).put("title",name.getText().toString().trim());String summary=mini.getString("title");if(type.equals("timer")){int minutes=Integer.parseInt(values.getText().toString().trim());if(minutes<1||minutes>1440)throw new IllegalArgumentException();mini.put("until",System.currentTimeMillis()+minutes*60000L);summary+=" · "+minutes+" мин";}else{JSONArray items=new JSONArray();for(String raw:values.getText().toString().split("\\n")){String value=raw.trim();if(value.isEmpty())continue;if(value.length()>160||items.length()>=20)throw new IllegalArgumentException();items.put(value);summary+="\n• "+value;}mini.put("items",items);}if(!valid(mini)||mini.optString("title").isEmpty())throw new IllegalArgumentException();JSONObject message=new JSONObject().put("kind","text").put("text",summary).put("mini",mini);if(a.activeSheet!=null)a.activeSheet.dismiss();if(chat.isEmpty())ChatSharing.choose(a,message);else ChatSharing.send(a,chat,message);}catch(Exception e){a.error(type.equals("timer")?"Укажите название и время от 1 до 1440 минут.":"Укажите название и от 2 до 20 вариантов, до 160 символов каждый.");}});a.sheet(title(type),b);}
 static List<JSONObject> updates(MainActivity a,JSONObject message,JSONObject mini)throws Exception{JSONArray all=a.vault.copy().getJSONArray("messages");List<JSONObject> result=new ArrayList<>();for(int i=0;i<all.length();i++){JSONObject m=all.getJSONObject(i),u=m.optJSONObject("mini_update");if(u!=null&&m.optString("peer").equals(message.optString("peer"))&&u.optString("id").equals(mini.optString("id"))&&u.optString("type").equals(mini.optString("type")))result.add(m);}result.sort(Comparator.comparingLong(m->m.optLong("time")));return result;}
 static void update(MainActivity a,JSONObject m,JSONObject tool,int choice,boolean done){try{String type=tool.optString("type");JSONObject update=new JSONObject().put("id",tool.getString("id")).put("type",type).put("choice",choice).put("done",done);String item=tool.getJSONArray("items").getString(choice);String text=type.equals("poll")?"Голос: "+item:type.equals("list")?(done?"☑ ":"☐ ")+item:"Выпало: "+item;ChatSharing.send(a,m.getString("peer"),new JSONObject().put("kind","text").put("text",text).put("mini_update",update));}catch(Exception e){a.error(Api.message(e));}}
 static void render(MainActivity a,LinearLayout box,JSONObject message)throws Exception{JSONObject tool=message.optJSONObject("mini");if(!valid(tool))return;String type=tool.getString("type");TextView heading=a.label(tool.optString("title"),18,a.TEXT);heading.setTypeface(null,Typeface.BOLD);box.addView(heading);a.space(box,8);if(type.equals("timer")){TextView time=a.label("",24,a.TEXT);box.addView(time);Runnable tick=new Runnable(){public void run(){long seconds=Math.max(0,(tool.optLong("until")-System.currentTimeMillis()+999)/1000);time.setText(seconds==0?"Время вышло":VideoLibraryStore.time(seconds));if(seconds>0&&!a.isDestroyed()&&a.screen.equals("chat")&&time.isAttachedToWindow())a.ui.postDelayed(this,1000);}};a.ui.post(tick);box.addView(a.button("Напомнить в конце",false,()->PersonalReminders.put(a,message,tool.optLong("until"))));return;}
  JSONArray items=tool.getJSONArray("items");List<JSONObject> changes=updates(a,message,tool);if(type.equals("poll")){Map<String,Integer> votes=new HashMap<>();for(JSONObject change:changes){int n=change.getJSONObject("mini_update").optInt("choice",-1);if(n>=0&&n<items.length())votes.put(change.optBoolean("out")?a.vault.nick():change.optString("from"),n);}for(int i=0;i<items.length();i++){int choice=i,count=0;for(int vote:votes.values())if(vote==i)count++;box.addView(a.button(items.getString(i)+" · "+count,Objects.equals(votes.get(a.vault.nick()),i),()->update(a,message,tool,choice,false)));a.space(box,5);}return;}
  if(type.equals("list")){boolean[] checked=new boolean[items.length()];for(JSONObject change:changes){JSONObject u=change.getJSONObject("mini_update");int n=u.optInt("choice",-1);if(n>=0&&n<checked.length)checked[n]=u.optBoolean("done");}for(int i=0;i<items.length();i++){int choice=i;CheckBox item=new CheckBox(a);item.setText(items.getString(i));item.setTextColor(a.TEXT);item.setChecked(checked[i]);item.setOnCheckedChangeListener((v,value)->update(a,message,tool,choice,value));box.addView(item);}return;}
  Wheel wheel=type.equals("wheel")?new Wheel(a,items):null;if(wheel!=null)box.addView(wheel,new LinearLayout.LayoutParams(a.dp(205),a.dp(205)));else a.paragraph(box,items.length()+" участников");if(!changes.isEmpty()){int selected=changes.get(changes.size()-1).getJSONObject("mini_update").optInt("choice",-1);if(selected>=0&&selected<items.length())box.addView(a.label("Выпало: "+items.getString(selected),17,a.TEXT));}box.addView(a.button(type.equals("wheel")?"Крутить колесо":"Выбрать случайно",true,()->{int choice=RANDOM.nextInt(items.length());if(wheel==null)update(a,message,tool,choice,false);else wheel.spin(choice,()->update(a,message,tool,choice,false));}));
 }
 static final class Wheel extends View{boolean spinning;final JSONArray items;void spin(int choice,Runnable complete){if(spinning)return;spinning=true;float target=getRotation()+1440+360-choice*360f/items.length();animate().rotation(target).setDuration(1800).setInterpolator(new android.view.animation.DecelerateInterpolator()).withEndAction(()->{spinning=false;complete.run();}).start();}final Paint p=new Paint(3);final int[] colors={0xff54bdb6,0xff9b83d8,0xffde798d,0xffd6b75f,0xff6a9dd2};Wheel(MainActivity a,JSONArray values){super(a);items=values;setContentDescription("Колесо: "+values.length()+" вариантов");}protected void onDraw(Canvas c){float d=Math.min(getWidth(),getHeight()),angle=360f/items.length();RectF bounds=new RectF(5,5,d-5,d-5);p.setStyle(Paint.Style.FILL);for(int i=0;i<items.length();i++){p.setColor(colors[i%colors.length]);c.drawArc(bounds,-90+i*angle,angle,true,p);}p.setColor(0xff142133);c.drawCircle(d/2,d/2,d*.17f,p);p.setColor(Color.WHITE);p.setTextSize(d*.12f);p.setTextAlign(Paint.Align.CENTER);c.drawText("✦",d/2,d*.54f,p);}}
 static void memory(MainActivity a){LinearLayout b=a.col();TextView status=a.label("Найдите четыре пары",16,a.TEXT);b.addView(status);GridLayout grid=new GridLayout(a);grid.setColumnCount(4);b.addView(grid);List<String> symbols=new ArrayList<>(Arrays.asList("🐈","🐕","🦊","🐼","🐈","🐕","🦊","🐼"));Collections.shuffle(symbols,RANDOM);TextView[] cards=new TextView[8];boolean[] matched=new boolean[8];int[] first={-1},moves={0};boolean[] busy={false};for(int i=0;i<8;i++){final int n=i;TextView card=a.button("?",false,()->{});cards[i]=card;card.setTextSize(28);card.setOnClickListener(v->{if(busy[0]||matched[n]||first[0]==n)return;card.setText(symbols.get(n));if(first[0]<0){first[0]=n;return;}int prior=first[0];first[0]=-1;moves[0]++;if(symbols.get(prior).equals(symbols.get(n))){matched[prior]=matched[n]=true;int pairs=0;for(boolean done:matched)if(done)pairs++;status.setText(pairs==8?"Готово! Ходов: "+moves[0]:"Пар: "+pairs/2+" из 4 · Ходов: "+moves[0]);}else{busy[0]=true;a.ui.postDelayed(()->{cards[prior].setText("?");card.setText("?");busy[0]=false;},700);}});GridLayout.LayoutParams lp=new GridLayout.LayoutParams();lp.width=a.dp(62);lp.height=a.dp(66);lp.setMargins(a.dp(3),a.dp(3),a.dp(3),a.dp(3));grid.addView(card,lp);}a.space(b,10);b.addView(a.button("Сыграть ещё",true,()->memory(a)));a.sheet("Парные символы",b);}
}
