package chat.oldy;

import android.content.Intent;
import android.graphics.Typeface;
import android.view.*;
import android.widget.*;

/** One destination for each function; Menu contains primary destinations only. */
final class NavigationPages {
 static void menu(MainActivity a){LinearLayout b=a.col();TextView note=a.label("ВАШ OLDI",12,a.MUTED);b.addView(note);a.space(b,10);View youtube=a.menuTile("▶","YouTube","Смотреть, искать и делиться видео",()->YouTubeBrowser.open(a,"https://m.youtube.com/"));youtube.setBackground(a.shape(a.light?0xffffe5ea:0xff552336,20));b.addView(youtube);a.space(b,10);GridLayout grid=new GridLayout(a);grid.setColumnCount(2);card(a,grid,"chat","Чаты","Разговоры и архив",a::chats);card(a,grid,"contacts","Контакты","Люди рядом",()->ContactDiscovery.show(a));card(a,grid,"profile","Моё","Профиль и сохранённое",()->SettingsHome.own(a));card(a,grid,"settings","Настройки","Всё под ваш ритм",a::settings);b.addView(grid);a.space(b,8);b.addView(a.menuTile("◉","Видеосвязь","Личные звонки и конференции",()->VideoCalls.show(a)));a.sheet("Меню",b);}
 static void home(MainActivity a){TextView back=a.button("⌂  Главная",false,a::chats);back.setContentDescription("Главная — чаты и YouTube");back.setGravity(Gravity.START|Gravity.CENTER_VERTICAL);a.root.addView(back,new LinearLayout.LayoutParams(-1,a.dp(44)));}
 static void card(MainActivity a,GridLayout grid,String icon,String title,String detail,Runnable action){LinearLayout tile=a.col();a.pad(tile,12);tile.setBackground(a.glass(19));UiIcon mark=new UiIcon(a,icon,a.GREEN);mark.setFocusable(false);tile.addView(mark,new LinearLayout.LayoutParams(a.dp(31),a.dp(31)));a.space(tile,8);TextView label=a.label(title,17,a.TEXT);label.setTypeface(null,Typeface.BOLD);tile.addView(label);a.space(tile,4);TextView sub=a.label(detail,12,a.MUTED);sub.setMaxLines(2);tile.addView(sub);tile.setContentDescription(title);tile.setOnClickListener(v->{if(a.activeSheet!=null)a.activeSheet.dismiss();action.run();});GridLayout.LayoutParams lp=new GridLayout.LayoutParams();lp.width=0;lp.height=a.dp(128);lp.columnSpec=GridLayout.spec(GridLayout.UNDEFINED,1f);lp.setMargins(a.dp(3),a.dp(3),a.dp(3),a.dp(3));grid.addView(tile,lp);}
 static void services(MainActivity a){a.base("services");a.title("Возможности",a::chats);ScrollView scroll=new RefreshScrollView(a);GridLayout grid=new GridLayout(a);grid.setColumnCount(2);scroll.addView(grid);a.root.addView(scroll,new LinearLayout.LayoutParams(-1,0,1));card(a,grid,"mic","Аудиомастерская","Запись и обработка",()->a.startActivity(new Intent(a,AudioLabActivity.class)));card(a,grid,"chat","Создать группу","Общение своим кругом",()->a.createRoom("group"));card(a,grid,"chat","Создать канал","Публикации и аудитория",()->a.createRoom("channel"));card(a,grid,"star","Капсула дня","Мысли и планы",a::capsule);card(a,grid,"contacts","Пульс общения","Ваш ритм общения",a::conversationStats);card(a,grid,"star","Парные символы","Мини-игра на память",()->MiniTools.memory(a));SideNavigation.navigation(a,-1);}
}
