package chat.oldy;

import android.graphics.Typeface;
import android.text.*;
import android.view.*;
import android.widget.*;
import org.json.*;
import java.util.*;

/** Notes live inside the active account's encrypted vault, including its backup. */
final class PersonalNotes {
 static JSONArray read(Vault v)throws Exception{JSONArray items=v.copy().optJSONArray("personal_notes");return items==null?new JSONArray():items;}
 static void put(Vault v,JSONObject note)throws Exception{synchronized(v){JSONArray old=read(v),next=new JSONArray();boolean found=false;for(int i=0;i<old.length();i++){JSONObject n=old.getJSONObject(i);if(n.optString("id").equals(note.getString("id"))){next.put(note);found=true;}else next.put(n);}if(!found){if(next.length()>=500)throw new Exception("Сохранено 500 заметок");next.put(note);}v.data.put("personal_notes",next);v.save();}}
 static void show(MainActivity a){a.base("notes");a.title("Заметки",()->SettingsHome.own(a));NavigationPages.home(a);EditText search=a.field(a.root,"Поиск в заметках",false);a.root.addView(a.button("＋ Новая заметка",true,()->edit(a,null)));ScrollView scroll=new ScrollView(a);LinearLayout list=a.col();scroll.addView(list);a.root.addView(scroll,new LinearLayout.LayoutParams(-1,0,1));
  Runnable render=()->{list.removeAllViews();try{List<JSONObject> notes=new ArrayList<>();JSONArray all=read(a.vault);String query=search.getText().toString().trim().toLowerCase(I18n.locale());for(int i=0;i<all.length();i++){JSONObject n=all.getJSONObject(i);if((n.optString("title")+" "+n.optString("body")).toLowerCase(I18n.locale()).contains(query))notes.add(n);}notes.sort((x,y)->{int pinned=Boolean.compare(y.optBoolean("pinned"),x.optBoolean("pinned"));return pinned!=0?pinned:Long.compare(y.optLong("updated"),x.optLong("updated"));});if(notes.isEmpty())a.paragraph(list,"Здесь будут ваши идеи, записи и планы.");for(JSONObject n:notes){a.space(list,8);LinearLayout card=a.col();a.pad(card,14);card.setBackground(a.glass(18));TextView title=a.label((n.optBoolean("pinned")?"★ ":"")+n.optString("title","Без названия"),18,a.TEXT);title.setTypeface(null,Typeface.BOLD);card.addView(title);TextView preview=a.label(n.optString("body"),14,a.MUTED);preview.setMaxLines(3);card.addView(preview);card.setOnClickListener(v->edit(a,n));list.addView(card);}}catch(Exception e){a.error(Api.message(e));}};
  search.addTextChangedListener(new TextWatcher(){public void beforeTextChanged(CharSequence s,int st,int count,int after){}public void onTextChanged(CharSequence s,int st,int before,int count){render.run();}public void afterTextChanged(Editable e){}});render.run();SideNavigation.navigation(a,3);
 }
 static void edit(MainActivity a,JSONObject source){final Vault owner=a.vault;final String id=source==null?UUID.randomUUID().toString():source.optString("id");a.base("note-editor");a.title("Заметка",()->show(a));NavigationPages.home(a);EditText title=a.field(a.root,"Название",false);title.setFilters(new InputFilter[]{new InputFilter.LengthFilter(160)});EditText body=new EditText(a);body.setTextColor(a.TEXT);body.setHintTextColor(a.MUTED);body.setBackground(a.glass(18));a.pad(body,14);body.setGravity(Gravity.TOP);body.setTextSize(17);body.setHint("Запишите мысль…");body.setInputType(InputType.TYPE_CLASS_TEXT|InputType.TYPE_TEXT_FLAG_MULTI_LINE|InputType.TYPE_TEXT_FLAG_CAP_SENTENCES|InputType.TYPE_TEXT_FLAG_AUTO_CORRECT);body.setFilters(new InputFilter[]{new InputFilter.LengthFilter(30000)});a.root.addView(body,new LinearLayout.LayoutParams(-1,0,1));CheckBox pin=new CheckBox(a);pin.setText("Закрепить заметку");pin.setTextColor(a.TEXT);a.root.addView(pin);TextView state=a.label("Изменения сохраняются автоматически",12,a.MUTED);a.root.addView(state);
  if(source!=null){title.setText(source.optString("title"));body.setText(source.optString("body"));pin.setChecked(source.optBoolean("pinned"));}
  Runnable save=()->{String t=title.getText().toString().trim(),b=body.getText().toString();boolean pinned=pin.isChecked();if(t.isEmpty()&&b.isEmpty()&&source==null)return;state.setText("Сохраняем…");a.work.execute(()->{try{if(owner.erased)return;put(owner,new JSONObject().put("id",id).put("title",t.isEmpty()?"Без названия":t).put("body",b).put("pinned",pinned).put("updated",System.currentTimeMillis()));a.runOnUiThread(()->state.setText("Сохранено"));}catch(Exception e){a.runOnUiThread(()->state.setText("Не удалось сохранить. "+Api.message(e)));}});};
  TextWatcher changes=new TextWatcher(){public void beforeTextChanged(CharSequence s,int st,int count,int after){}public void onTextChanged(CharSequence s,int st,int before,int count){save.run();}public void afterTextChanged(Editable e){}};title.addTextChangedListener(changes);body.addTextChangedListener(changes);pin.setOnCheckedChangeListener((v,checked)->save.run());a.root.addView(a.button("Готово",true,()->{save.run();a.work.execute(()->a.runOnUiThread(()->{if(a.vault==owner&&a.screen.equals("note-editor"))show(a);}));}));
 }
}
