package chat.oldy;

import android.app.*;
import android.content.*;
import android.net.Uri;
import android.os.Build;
import android.widget.*;
import org.json.*;
import java.util.*;

/** Reminders contain message IDs in the account's encrypted vault, never message text in alarms. */
public final class PersonalReminders extends BroadcastReceiver {
 static JSONObject entries(Vault v)throws Exception{synchronized(v){JSONObject b=v.data.optJSONObject("reminders");if(b==null){b=new JSONObject();v.data.put("reminders",b);}return b;}}
 static PendingIntent alarm(Context c,String account,String id){Intent i=new Intent(c,PersonalReminders.class).setData(Uri.parse("oldy-reminder://"+account+"/"+id)).putExtra("account",account).putExtra("mid",id);return PendingIntent.getBroadcast(c,0,i,PendingIntent.FLAG_IMMUTABLE|PendingIntent.FLAG_UPDATE_CURRENT);}
 static void schedule(Context c,String account,String id,long at){c.getSystemService(AlarmManager.class).setAndAllowWhileIdle(AlarmManager.RTC_WAKEUP,Math.max(at,System.currentTimeMillis()+1000),alarm(c,account,id));}
 static void put(MainActivity a,JSONObject message,long at){if(at<=System.currentTimeMillis()){a.error("Выберите время в будущем");return;}try{Vault v=a.vault;String id=message.getString("id");synchronized(v){entries(v).put(id,new JSONObject().put("at",at).put("peer",message.getString("peer")));v.save();}schedule(a,v.nick(),id,at);Toast.makeText(a,"Напоминание: "+format(at),Toast.LENGTH_LONG).show();}catch(Exception e){a.error(Api.message(e));}}
 static String format(long at){return new java.text.SimpleDateFormat("d MMM, HH:mm",I18n.locale()).format(new Date(at));}
 static void choose(MainActivity a,JSONObject message){LinearLayout b=a.col();String[] labels={"Через 1 час","Завтра","Через неделю","Выбрать дату"};long now=System.currentTimeMillis();long[] offsets={3600000,86400000,604800000};for(int n=0;n<labels.length;n++){final int i=n;b.addView(a.button(labels[n],false,()->{if(i<3)put(a,message,now+offsets[i]);else{Calendar date=Calendar.getInstance();new DatePickerDialog(a,(view,y,m,d)->{date.set(y,m,d);new TimePickerDialog(a,(time,h,min)->{date.set(Calendar.HOUR_OF_DAY,h);date.set(Calendar.MINUTE,min);date.set(Calendar.SECOND,0);put(a,message,date.getTimeInMillis());},date.get(Calendar.HOUR_OF_DAY),date.get(Calendar.MINUTE),true).show();},date.get(Calendar.YEAR),date.get(Calendar.MONTH),date.get(Calendar.DAY_OF_MONTH)).show();}}));a.space(b,7);}a.sheet("Напомнить о сообщении",b);}
 static void show(MainActivity a){try{LinearLayout b=PersonalHub.page(a,"Напоминания");JSONObject items; synchronized(a.vault){items=new JSONObject(entries(a.vault).toString());}List<String> ids=new ArrayList<>();items.keys().forEachRemaining(ids::add);ids.sort(Comparator.comparingLong(id->items.optJSONObject(id).optLong("at")));if(ids.isEmpty())a.paragraph(b,"Удерживайте сообщение и выберите «Напомнить».");for(String id:ids){JSONObject item=items.getJSONObject(id),message=a.vault.message(id);String text=message==null?"Сообщение недоступно":Payload.preview(message);LinearLayout card=a.col();a.pad(card,12);card.setBackground(a.glass(18));card.addView(a.label(format(item.optLong("at"))+(item.optBoolean("fired")?" · Напомнили":""),13,a.MUTED));TextView title=a.label(text,16,a.TEXT);title.setMaxLines(3);card.addView(title);card.setOnClickListener(v->{if(message!=null)PersonalHub.open(a,message);});card.setOnLongClickListener(v->{a.dialog().setTitle("Отменить напоминание?").setPositiveButton("Отменить",(d,w)->{try{synchronized(a.vault){entries(a.vault).remove(id);a.vault.save();}a.getSystemService(AlarmManager.class).cancel(alarm(a,a.vault.nick(),id));show(a);}catch(Exception e){a.error(Api.message(e));}}).setNegativeButton("Оставить",null).show();return true;});b.addView(card);a.space(b,8);}}catch(Exception e){a.error(Api.message(e));}}
 static void restore(Context c){try{Vault v=ChatService.vault(c);if(v.token().isEmpty())return;JSONObject items; synchronized(v){items=new JSONObject(entries(v).toString());}Iterator<String> ids=items.keys();while(ids.hasNext()){String id=ids.next();JSONObject r=items.getJSONObject(id);if(!r.optBoolean("fired"))schedule(c,v.nick(),id,r.optLong("at"));}}catch(Exception ignored){}}
 public void onReceive(Context c,Intent intent){if(Intent.ACTION_BOOT_COMPLETED.equals(intent.getAction())){restore(c);return;}try{Vault v=ChatService.vault(c);String id=intent.getStringExtra("mid");if(!v.nick().equals(intent.getStringExtra("account"))||v.token().isEmpty()||id==null)return;JSONObject m=v.message(id),r; synchronized(v){r=entries(v).optJSONObject(id);}if(r==null||r.optBoolean("fired")||m==null)return;if(r.optLong("at")>System.currentTimeMillis()+1000){schedule(c,v.nick(),id,r.getLong("at"));return;}NotificationManager nm=c.getSystemService(NotificationManager.class);if(!nm.areNotificationsEnabled())return;String channel="oldi-reminders";nm.createNotificationChannel(new NotificationChannel(channel,"Напоминания",NotificationManager.IMPORTANCE_DEFAULT));Intent open=new Intent(c,MainActivity.class).putExtra("chat",m.optString("peer")).putExtra("message",id).putExtra("reminder_account",v.nick()).setData(Uri.parse("oldy-reminder://"+v.nick()+"/"+id));PendingIntent pi=PendingIntent.getActivity(c,0,open,PendingIntent.FLAG_IMMUTABLE|PendingIntent.FLAG_UPDATE_CURRENT);Notification n=new Notification.Builder(c,channel).setSmallIcon(R.drawable.ic_launcher).setContentTitle("Вы просили напомнить").setContentText(Notices.prefs(c).getBoolean("preview",false)?Payload.preview(m):"Откройте сообщение в Oldi Chat").setContentIntent(pi).setAutoCancel(true).setVisibility(Notification.VISIBILITY_PRIVATE).build();nm.notify("reminder:"+v.nick(),id.hashCode(),n);synchronized(v){entries(v).getJSONObject(id).put("fired",true);v.save();}}catch(Exception ignored){}}
}
