package chat.oldy;
import android.Manifest;import android.app.*;import android.content.*;import android.content.pm.PackageManager;import android.os.*;import android.view.*;import android.widget.*;import org.webrtc.*;import java.util.*;

/** Native video surfaces; camera/microphone permissions are requested only on acceptance. */
public final class VideoCallActivity extends Activity {
 static volatile VideoCallActivity active;ConferenceCall.Session call;final Handler ui=new Handler(Looper.getMainLooper());GridLayout grid;LinearLayout actions;TextView state,accept,camera,microphone;final Map<String,Tile> tiles=new LinkedHashMap<>();boolean resumed;
 public void onCreate(Bundle b){super.onCreate(b);call=ConferenceCall.current;if(call==null||getIntent().hasExtra("cid")&&!call.id.equals(getIntent().getStringExtra("cid"))){finish();return;}active=this;getWindow().addFlags(WindowManager.LayoutParams.FLAG_KEEP_SCREEN_ON);LinearLayout root=new ThemeLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setPadding(dp(12),dp(36),dp(12),dp(20));root.setOnApplyWindowInsetsListener((v,insets)->{v.setPadding(dp(12)+insets.getSystemWindowInsetLeft(),dp(12)+insets.getSystemWindowInsetTop(),dp(12)+insets.getSystemWindowInsetRight(),dp(12)+insets.getSystemWindowInsetBottom());return insets;});TextView home=button("⌂  Главная",()->{startActivity(new Intent(this,MainActivity.class).addFlags(Intent.FLAG_ACTIVITY_CLEAR_TOP|Intent.FLAG_ACTIVITY_SINGLE_TOP));finish();});root.addView(home);state=label("Видеосвязь",21);root.addView(state);grid=new GridLayout(this);grid.setColumnCount(2);root.addView(grid,new LinearLayout.LayoutParams(-1,0,1));accept=button("Ответить на видеозвонок",this::accept);root.addView(accept);actions=new LinearLayout(this);microphone=button("Микрофон",()->{call.mute();update();});camera=button("Камера",()->{call.camera();update();});actions.addView(microphone,new LinearLayout.LayoutParams(0,-2,1));actions.addView(camera,new LinearLayout.LayoutParams(0,-2,1));root.addView(actions);LinearLayout controls=new LinearLayout(this);controls.addView(button("↻ Камера",()->call.flip()),new LinearLayout.LayoutParams(0,-2,1));TextView end=button("Завершить",()->{call.end("Видеозвонок завершён",true);finish();});end.setTextColor(0xffff7388);controls.addView(end,new LinearLayout.LayoutParams(0,-2,1));root.addView(controls);setContentView(root);if(!call.incoming||getIntent().getBooleanExtra("accept",false))accept();}
 int dp(int value){return Math.round(value*getResources().getDisplayMetrics().density);}int color(){return Notices.prefs(this).getString("theme","dark").equals("light")?0xff20354b:0xffe2efff;}
 TextView label(String text,int size){TextView t=new TextView(this);t.setText(text);t.setTextColor(color());t.setTextSize(size);t.setPadding(dp(8),dp(8),dp(8),dp(8));return t;}
 TextView button(String text,Runnable click){TextView t=label(text,16);t.setMinHeight(dp(50));t.setGravity(Gravity.CENTER);t.setOnClickListener(v->click.run());return t;}
 void accept(){if(call.closed)return;List<String> missing=new ArrayList<>();for(String p:new String[]{Manifest.permission.CAMERA,Manifest.permission.RECORD_AUDIO})if(checkSelfPermission(p)!=PackageManager.PERMISSION_GRANTED)missing.add(p);if(!missing.isEmpty()){requestPermissions(missing.toArray(new String[0]),84);return;}call.start();update();}
 public void onRequestPermissionsResult(int code,String[] permissions,int[] results){super.onRequestPermissionsResult(code,permissions,results);if(code==84){for(int r:results)if(r!=PackageManager.PERMISSION_GRANTED){call.end("Для видеозвонка нужен доступ к камере и микрофону",true);finish();return;}accept();}}
 protected void onResume(){super.onResume();resumed=true;active=this;ui.post(tick);}
 protected void onPause(){resumed=false;ui.removeCallbacks(tick);super.onPause();}
 protected void onStop(){releaseViews();super.onStop();}
 protected void onDestroy(){ui.removeCallbacksAndMessages(null);releaseViews();if(active==this)active=null;super.onDestroy();}
 final Runnable tick=new Runnable(){public void run(){if(!resumed||isFinishing())return;update();ui.postDelayed(this,400);}};
 void update(){if(call==null||call.closed){finish();return;}accept.setVisibility(call.accepted?View.GONE:View.VISIBLE);actions.setVisibility(call.ready?View.VISIBLE:View.GONE);microphone.setText(call.muted?"Микрофон выкл.":"Микрофон вкл.");camera.setText(call.cameraOff?"Камера выкл.":"Камера вкл.");long elapsed=call.connectedAt==0?0:(SystemClock.elapsedRealtime()-call.connectedAt)/1000;state.setText(call.state+(elapsed>0?String.format(Locale.ROOT," · %d:%02d",elapsed/60,elapsed%60):""));if(!call.ready)return;
  add(call.vault.nick(),call.local,true);for(String peer:call.invited)if(!peer.equals(call.vault.nick()))add(peer,call.pictures.get(peer),false);
 }
 void add(String peer,ConferenceCall.Sink sink,boolean self){Tile tile=tiles.get(peer);if(tile==null){tile=new Tile();tile.box=new LinearLayout(this);tile.box.setOrientation(LinearLayout.VERTICAL);tile.box.setBackgroundColor(0xff172332);tile.name=label(self?"Вы":"@"+peer,14);tile.name.setTextColor(0xffe2efff);tile.box.addView(tile.name);GridLayout.LayoutParams lp=new GridLayout.LayoutParams();lp.width=0;lp.height=0;lp.columnSpec=GridLayout.spec(GridLayout.UNDEFINED,1f);lp.rowSpec=GridLayout.spec(GridLayout.UNDEFINED,1f);lp.setMargins(dp(3),dp(3),dp(3),dp(3));grid.addView(tile.box,lp);tiles.put(peer,tile);}tile.name.setText(self?(call.cameraOff?"Вы · камера выключена":"Вы"):"@"+peer+" · "+call.states.getOrDefault(peer,"Приглашение"));if(sink!=null&&tile.sink!=sink){if(tile.sink!=null)tile.sink.target=null;if(tile.video==null){tile.video=new SurfaceViewRenderer(this);tile.video.init(call.egl.getEglBaseContext(),null);tile.video.setScalingType(RendererCommon.ScalingType.SCALE_ASPECT_FIT);tile.video.setEnableHardwareScaler(true);tile.video.setMirror(self);tile.video.setFpsReduction(20);tile.box.addView(tile.video,new LinearLayout.LayoutParams(-1,0,1));}tile.sink=sink;sink.target=tile.video;}if(self&&tile.video!=null)tile.video.setVisibility(call.cameraOff?View.INVISIBLE:View.VISIBLE);}
 void releaseViews(){for(Tile t:tiles.values()){if(t.sink!=null)t.sink.target=null;if(t.video!=null)t.video.release();}tiles.clear();if(grid!=null)grid.removeAllViews();}
 static void detach(ConferenceCall.Session s){VideoCallActivity a=active;if(a!=null&&a.call==s){a.releaseViews();a.finish();}}
 static final class Tile {LinearLayout box;TextView name;SurfaceViewRenderer video;ConferenceCall.Sink sink;}
}
