package chat.oldy;
import android.text.*;import android.view.*;import android.widget.*;import org.json.*;import java.util.*;

/** Choose participants from existing conversations, contacts, or account search. */
final class VideoCalls {
 static void show(MainActivity a){a.base("video-calls");a.title("Видеосвязь",a::chats);NavigationPages.home(a);if(ConferenceCall.current!=null){a.root.addView(a.button("Вернуться в текущий звонок",true,()->a.startActivity(new android.content.Intent(a,VideoCallActivity.class))));}
  final Vault owner=a.vault;final View page=a.root;LinkedHashMap<String,JSONObject> selected=new LinkedHashMap<>();EditText query=a.field(a.root,"Имя или @ник",false);LinearLayout tabs=a.row();final boolean[] chatsOnly={true};ScrollView scroll=new ScrollView(a);LinearLayout list=a.col();scroll.addView(list);TextView status=a.label("Выберите от 1 до 4 собеседников",13,a.MUTED);a.root.addView(status);
  final LinkedHashMap<String,JSONObject> people=new LinkedHashMap<>();try{JSONObject contacts=owner.copy().getJSONObject("contacts");Iterator<String> keys=contacts.keys();while(keys.hasNext()){String nick=keys.next();people.put(nick,contacts.getJSONObject(nick));}}catch(Exception ignored){}
  final Set<String> chats=new HashSet<>();try{JSONArray messages=owner.copy().getJSONArray("messages");for(int i=0;i<messages.length();i++){String peer=messages.getJSONObject(i).optString("peer");if(peer.matches("[a-z0-9_]{3,24}"))chats.add(peer);}}catch(Exception ignored){}
  Runnable render=()->{list.removeAllViews();String q=query.getText().toString().trim().toLowerCase(I18n.locale()).replaceFirst("^@","");for(Map.Entry<String,JSONObject> entry:people.entrySet()){String nick=entry.getKey();JSONObject user=entry.getValue();if(nick.equals(owner.nick())||owner.isBlocked(nick)||chatsOnly[0]&&q.isEmpty()&&!chats.contains(nick))continue;if(!q.isEmpty()&&!(nick+" "+user.optString("name")).toLowerCase(I18n.locale()).contains(q))continue;CheckBox row=new CheckBox(a);row.setText(user.optString("name",nick)+"  @"+nick);row.setTextColor(a.TEXT);row.setTextSize(16);row.setMinHeight(a.dp(58));row.setChecked(selected.containsKey(nick));row.setOnCheckedChangeListener((v,checked)->{if(checked){if(selected.size()>=4&&!selected.containsKey(nick)){row.setChecked(false);a.error("В одной конференции до 5 участников, включая вас");return;}selected.put(nick,user);}else selected.remove(nick);status.setText(selected.isEmpty()?"Выберите собеседников":"Выбрано: "+String.join(", ",selected.keySet()));});list.addView(row);}if(list.getChildCount()==0)a.paragraph(list,"Найдите собеседника по имени или @нику.");};
  tabs.addView(a.button("Из чатов",false,()->{chatsOnly[0]=true;render.run();}),new LinearLayout.LayoutParams(0,a.dp(48),1));tabs.addView(a.button("Все контакты",false,()->{chatsOnly[0]=false;render.run();}),new LinearLayout.LayoutParams(0,a.dp(48),1));a.root.addView(tabs);a.root.addView(scroll,new LinearLayout.LayoutParams(-1,0,1));a.root.addView(a.button("Начать видеозвонок",true,()->{if(selected.isEmpty()){a.error("Выберите хотя бы одного собеседника");return;}try{for(JSONObject person:selected.values())owner.pin(person);ConferenceCall.dial(a,new ArrayList<>(selected.keySet()));}catch(Exception e){a.error(Api.message(e));}}));SideNavigation.navigation(a,0);
  query.addTextChangedListener(new TextWatcher(){int sequence;Runnable pending;public void beforeTextChanged(CharSequence s,int st,int count,int after){}public void afterTextChanged(Editable e){}public void onTextChanged(CharSequence s,int st,int before,int count){render.run();int seq=++sequence;if(pending!=null)a.ui.removeCallbacks(pending);String q=s.toString().trim();if(q.length()<2)return;pending=()->a.work.execute(()->{try{JSONArray results=a.api.call("/search?q="+java.net.URLEncoder.encode(q,"UTF-8"),null,owner.token()).getJSONArray("users");a.runOnUiThread(()->{if(seq!=sequence||a.root!=page||a.vault!=owner)return;for(int i=0;i<results.length();i++){JSONObject u=results.optJSONObject(i);people.put(u.optString("nick"),u);}render.run();});}catch(Exception ignored){}});a.ui.postDelayed(pending,350);}});render.run();
 }
}
