package chat.oldy;
import android.app.*;import android.content.*;import android.graphics.Color;import android.graphics.drawable.GradientDrawable;import android.net.*;import android.net.http.SslError;import android.os.*;import android.view.*;import android.webkit.*;import android.widget.*;
import java.util.concurrent.*;

/** The official YouTube site stays inside Oldi. No extraction, ad removal, cookie
 * export, JavaScript bridge or implicit external activity is used. */
public final class YouTubeHubActivity extends Activity {
 static final int VPN=731;final Handler ui=new Handler(Looper.getMainLooper());final ExecutorService work=Executors.newSingleThreadExecutor();
 ThemeLayout root;WebView web;FrameLayout content;TextView status;ProgressBar progress;EditText search;String url="https://m.youtube.com/";
 VideoLibraryStore library;String observedVideo="";double observedPosition;
 boolean pageFailed;boolean local,starting,foreground,permission,loaded,browserActive,browserPaused;int attempt;long lastRestart;View fullscreen;WebChromeClient.CustomViewCallback fullscreenCallback;
 public void onCreate(Bundle state){super.onCreate(state);I18n.init(this);try{library=new VideoLibraryStore(this,ChatService.vault(this).nick());}catch(Exception ignored){}String initial=getIntent().getStringExtra("url");if(YouTubeBrowser.url(initial))url=initial;root=new ThemeLayout(this);setContentView(root);getWindow().setStatusBarColor(Color.TRANSPARENT);getWindow().setNavigationBarColor(Color.TRANSPARENT);if(Build.VERSION.SDK_INT>=30)getWindow().setDecorFitsSystemWindows(false);
  root.setOnApplyWindowInsetsListener((v,i)->{v.setPadding(dp(8)+i.getSystemWindowInsetLeft(),i.getSystemWindowInsetTop(),dp(8)+i.getSystemWindowInsetRight(),i.getSystemWindowInsetBottom());return i;});
  LinearLayout head=new LinearLayout(this);head.setGravity(Gravity.CENTER_VERTICAL);head.addView(key("‹",()->onBackPressed()),new LinearLayout.LayoutParams(dp(46),dp(48)));TextView heading=key("▶ YouTube",()->navigate("https://m.youtube.com/"));head.addView(heading,new LinearLayout.LayoutParams(0,dp(48),1));head.addView(key("⋮",this::menu),new LinearLayout.LayoutParams(dp(46),dp(48)));root.addView(head);
  LinearLayout find=new LinearLayout(this);search=new EditText(this);search.setSingleLine(true);search.setTextSize(15);search.setTextColor(Color.WHITE);search.setHintTextColor(0xffd4b9c1);search.setHint(tr("Поиск видео в YouTube","Search YouTube"));search.setImeOptions(android.view.inputmethod.EditorInfo.IME_ACTION_SEARCH);search.setBackground(shape(0xe72a2032));search.setPadding(dp(12),0,dp(6),0);search.setOnEditorActionListener((v,a,e)->{if(a==android.view.inputmethod.EditorInfo.IME_ACTION_SEARCH){search();return true;}return false;});find.addView(search,new LinearLayout.LayoutParams(0,dp(46),1));find.addView(key("⌕",this::search),new LinearLayout.LayoutParams(dp(48),dp(46)));root.addView(find);
  status=new TextView(this);status.setTextSize(11);status.setTextColor(Notices.prefs(this).getString("theme","dark").equals("light")?0xff612439:0xffffb9cd);status.setPadding(dp(8),dp(7),dp(8),dp(7));status.setOnClickListener(v->information());root.addView(status);progress=new ProgressBar(this,null,android.R.attr.progressBarStyleHorizontal);progress.setMax(100);root.addView(progress,new LinearLayout.LayoutParams(-1,dp(3)));content=new FrameLayout(this);root.addView(content,new LinearLayout.LayoutParams(-1,0,1));YouTubeWebRoute.retain();createWeb();if(state!=null&&YouTubeBrowser.url(state.getString("url")))url=state.getString("url");ui.post(this::choose);
 }
 static String tr(String ru,String en){return I18n.language().equals("en")?en:ru;}
 void createWeb(){web=new WebView(this);content.addView(web,new FrameLayout.LayoutParams(-1,-1));WebSettings s=web.getSettings();s.setJavaScriptEnabled(true);s.setDomStorageEnabled(true);s.setAllowFileAccess(false);s.setAllowContentAccess(false);s.setMixedContentMode(WebSettings.MIXED_CONTENT_NEVER_ALLOW);s.setMediaPlaybackRequiresUserGesture(true);s.setJavaScriptCanOpenWindowsAutomatically(false);s.setSupportMultipleWindows(false);s.setGeolocationEnabled(false);s.setSafeBrowsingEnabled(true);CookieManager.getInstance().setAcceptThirdPartyCookies(web,true);
  web.setDownloadListener((u,a,d,m,l)->status.setText(tr("Загрузка YouTube-видео не поддерживается","YouTube video downloading is not supported")));
  web.setWebViewClient(new WebViewClient(){
   public boolean shouldOverrideUrlLoading(WebView v,WebResourceRequest r){if(!r.isForMainFrame())return !"https".equals(r.getUrl().getScheme());String u=r.getUrl().toString();if(YouTubeBrowser.url(u))return false;String h=r.getUrl().getHost();if(h!=null&&(h.equals("accounts.google.com")||h.equals("accounts.google.ru"))){status.setText(tr("Для входа используйте пункт «Мой аккаунт YouTube» в меню","To sign in, use My YouTube account in the menu"));return true;}if(r.hasGesture())new AlertDialog.Builder(YouTubeHubActivity.this).setMessage(tr("Открыть эту ссылку во внешнем приложении?","Open this link in an external app?")).setPositiveButton(I18n.t("Открыть"),(d,w)->external(u)).setNegativeButton(I18n.t("Отмена"),null).show();return true;}
   public void onPageStarted(WebView v,String u,android.graphics.Bitmap icon){pageFailed=false;progress.setVisibility(View.VISIBLE);if(YouTubeBrowser.url(u))url=u;}
   public void onPageFinished(WebView v,String u){progress.setVisibility(View.GONE);loaded=!pageFailed;if(!pageFailed)connectionLabel();}
   public void onReceivedError(WebView v,WebResourceRequest r,WebResourceError e){if(r.isForMainFrame()){pageFailed=true;progress.setVisibility(View.GONE);status.setText(tr("YouTube не загрузился. ⋮ → Проверить соединение","YouTube did not load. ⋮ → Check connection"));}}
   public void onReceivedSslError(WebView v,SslErrorHandler handler,SslError e){handler.cancel();status.setText(tr("Сертификат YouTube не прошёл проверку","YouTube certificate verification failed"));}
   public boolean onRenderProcessGone(WebView v,RenderProcessGoneDetail d){content.removeView(v);v.destroy();web=null;status.setText(tr("Плеер остановился. Нажмите ⋮ → Обновить","Player stopped. Tap ⋮ → Reload"));return true;}
  });
  web.setWebChromeClient(new WebChromeClient(){public void onProgressChanged(WebView v,int n){progress.setProgress(n);}public void onPermissionRequest(PermissionRequest request){request.deny();}public void onGeolocationPermissionsShowPrompt(String origin,GeolocationPermissions.Callback cb){cb.invoke(origin,false,false);}public void onShowCustomView(View v,CustomViewCallback cb){if(fullscreen!=null){cb.onCustomViewHidden();return;}fullscreen=v;fullscreenCallback=cb;((FrameLayout)getWindow().getDecorView()).addView(v,new FrameLayout.LayoutParams(-1,-1));getWindow().getDecorView().setSystemUiVisibility(5894);}public void onHideCustomView(){hideFullscreen();}});
 }
 void search(){String q=search.getText().toString().trim();if(q.isEmpty())return;((android.view.inputmethod.InputMethodManager)getSystemService(INPUT_METHOD_SERVICE)).hideSoftInputFromWindow(search.getWindowToken(),0);search.clearFocus();navigate("https://m.youtube.com/results?search_query="+Uri.encode(q));}
 void navigate(String next){if(!YouTubeBrowser.url(next)||isFinishing())return;if(!TunnelStateRepository.on()){status.setText(tr("Подключение YouTube прервано","YouTube connection interrupted"));return;}url=next;if(web==null)createWeb();YouTubeWebRoute.apply(()->{if(web!=null&&!isFinishing())web.loadUrl(url);},this::routeUnavailable);}
 void routeUnavailable(){if(web!=null)web.stopLoading();status.setText(tr("Обновите Android System WebView для просмотра YouTube","Update Android System WebView to watch YouTube"));}
 void choose(){if(starting||isFinishing())return;if(!YouTubeWebRoute.supported()){routeUnavailable();return;}if(!MediaService.configured(this)){status.setText(tr("Подключение YouTube пока недоступно","YouTube connection is not available yet"));return;}permit();}
 void consent(){choose();}
 void permit(){try{Intent request=VpnService.prepare(this);if(request==null)startLocal(false);else{permission=true;startActivityForResult(request,VPN);}}catch(Exception e){status.setText(tr("Android не разрешил запуск локального режима","Android could not start local mode"));}}
 protected void onActivityResult(int r,int result,Intent data){super.onActivityResult(r,result,data);if(r==VPN){permission=false;if(result==RESULT_OK)startLocal(false);else{local=false;status.setText(tr("Для просмотра разрешите соединение Oldi","Allow the Oldi connection to watch"));}}}
 void startLocal(boolean restart){if(starting||isFinishing())return;local=true;starting=true;lastRestart=SystemClock.elapsedRealtime();int token=++attempt;status.setText(tr("Подключаем YouTube…","Connecting YouTube…"));if(restart)LocalTunnelService.stop(this);ui.postDelayed(()->startAfterStop(token,SystemClock.elapsedRealtime()+6000,restart),restart?200:0);}
 void startAfterStop(int token,long deadline,boolean restart){if(token!=attempt||isFinishing())return;if(restart&&(TunnelStateRepository.on()||NetworkDiagnostics.otherVpn(this))){if(SystemClock.elapsedRealtime()<deadline){ui.postDelayed(()->startAfterStop(token,deadline,true),150);return;}starting=false;status.setText(tr("Предыдущий VPN ещё отключается. Повторите.","The previous VPN is still disconnecting. Retry."));return;}try{LocalTunnelService.start(this);awaitTunnel(token,SystemClock.elapsedRealtime()+65000);}catch(Exception e){starting=false;status.setText(tr("Локальный модуль не запустился","Local module failed to start"));}}
 void awaitTunnel(int token,long deadline){if(token!=attempt||isFinishing())return;if(TunnelStateRepository.on()){starting=false;connectionLabel();navigate(url);return;}if(SystemClock.elapsedRealtime()-lastRestart>1500&&TunnelStateRepository.state.equals("OFF")&&!TunnelStateRepository.error.isEmpty()){starting=false;status.setText(tr("Не удалось подключить YouTube. Код: ","Could not connect YouTube. Code: ")+TunnelStateRepository.error);return;}if(SystemClock.elapsedRealtime()<deadline)ui.postDelayed(()->awaitTunnel(token,deadline),150);else{starting=false;status.setText(tr("Не удалось подключить YouTube. ⋮ → Проверить соединение","Could not start local mode. ⋮ → Diagnostics"));}}
 void connectionLabel(){if(starting)return;status.setText(local&&TunnelStateRepository.on()?tr("YouTube · соединение Oldi","YouTube · Oldi connection"):tr("Подключаем YouTube…","Connecting YouTube…"));}
 void information(){diagnostics();}
 void menu(){String[] options={tr("Обновить","Reload"),tr("История просмотренного","Watch history"),tr("Избранные ролики","Favorite videos"),tr("Добавить в избранное","Toggle favorite"),tr("Отправить ролик в чат","Send video to chat"),tr("Смотреть в плеере","Watch in player"),tr("Мой аккаунт YouTube","My YouTube account"),tr("Проверить соединение","Check connection")};new AlertDialog.Builder(this).setItems(options,(d,w)->{if(w==0)choose();else if(w==1||w==2)startActivity(new Intent(this,MainActivity.class).putExtra("video_tab",w==1?"history":"favorite").addFlags(Intent.FLAG_ACTIVITY_CLEAR_TOP|Intent.FLAG_ACTIVITY_SINGLE_TOP));else if(w==6)googleSignIn();else if(w==7)diagnostics();else{YouTubeLinkDetector.Target target=YouTubeLinkDetector.parse(url);if(target==null||target.videoId.isEmpty()){status.setText(tr("Сначала откройте видео","Open a video first"));return;}if(w==3&&library!=null){work.execute(()->{try{library.toggle(target.videoId,"favorite");boolean saved=library.get(target.videoId).optBoolean("favorite");runOnUiThread(()->Toast.makeText(this,tr(saved?"Ролик в избранном":"Ролик убран из избранного",saved?"Video saved":"Video removed"),Toast.LENGTH_SHORT).show());}catch(Exception e){runOnUiThread(()->status.setText(tr("Не удалось сохранить ролик","Could not save video")));}});}else if(w==4)startActivity(new Intent(this,MainActivity.class).putExtra("share_youtube",target.url()).addFlags(Intent.FLAG_ACTIVITY_CLEAR_TOP|Intent.FLAG_ACTIVITY_SINGLE_TOP));else if(w==5)OldiYouTubePlayer.open(this,target,"YouTube");}}).show();}
 void rememberPlayback(){if(web==null||!loaded||library==null)return;web.evaluateJavascript("JSON.stringify({url:location.href,title:document.title,time:document.querySelector('video')?.currentTime||0,duration:document.querySelector('video')?.duration||0,playing:!!document.querySelector('video')&&!document.querySelector('video').paused})",raw->{if(isDestroyed()||raw==null||raw.length()>5000)return;try{Object value=new org.json.JSONTokener(raw).nextValue();if(!(value instanceof String))return;org.json.JSONObject state=new org.json.JSONObject((String)value);YouTubeLinkDetector.Target target=YouTubeLinkDetector.parse(state.optString("url"));if(target==null||target.videoId.isEmpty())return;double position=state.optDouble("time"),duration=state.optDouble("duration"),watched=state.optBoolean("playing")&&target.videoId.equals(observedVideo)?Math.min(3,Math.max(0,position-observedPosition)):0;observedVideo=target.videoId;observedPosition=position;if(YouTubeBrowser.url(state.optString("url")))url=state.optString("url");work.execute(()->{try{library.update(target.videoId,state.optString("title"),position,duration,watched);}catch(Exception ignored){}});}catch(Exception ignored){}});}
 void strategies(){String[] values={"auto","split","disorder","fake4","fake8"};String[] names={tr("Автоматически · 5 вариантов","Automatic · 5 strategies"),tr("Разделение TLS","TLS splitting"),tr("Порядок пакетов","Packet order"),tr("Дополнительный режим 1","Additional mode 1"),tr("Дополнительный режим 2","Additional mode 2")};new AlertDialog.Builder(this).setTitle(tr("Подобрать соединение","Find connection")).setItems(names,(d,w)->{Notices.prefs(this).edit().putString("youtube_dpi_strategy",values[w]).apply();if(VpnService.prepare(this)==null)startLocal(true);else consent();}).setNeutralButton(tr("Что проверить","What to check"),(d,w)->information()).show();}
 void diagnostics(){status.setText(I18n.t("Проверяем соединение…"));work.execute(()->{org.json.JSONObject r=NetworkDiagnostics.check(this);runOnUiThread(()->{if(isFinishing())return;String report=YouTubeSettings.format(r);new AlertDialog.Builder(this).setTitle(tr("Проверка YouTube","YouTube diagnostics")).setMessage(report).setPositiveButton(I18n.t("Закрыть"),null).setNeutralButton(tr("Скопировать","Copy"),(d,w)->getSystemService(ClipboardManager.class).setPrimaryClip(ClipData.newPlainText("Oldi diagnostics",report))).show();});});}
 void googleSignIn(){if(!TunnelStateRepository.on()){choose();return;}if(YouTubeBrowser.account(this,url)){browserActive=true;LocalTunnelService.browser(this,true);}else status.setText(tr("Для входа нужен браузер с поддержкой вкладок приложения","A browser supporting in-app tabs is needed to sign in"));}
 void external(String u){try{Uri uri=Uri.parse(u);if(!"https".equals(uri.getScheme())||uri.getHost()==null||uri.getUserInfo()!=null)return;startActivity(new Intent(Intent.ACTION_VIEW,uri));}catch(Exception ignored){}}
 final Runnable heartbeat=new Runnable(){public void run(){if(!foreground)return;rememberPlayback();if(local){if(TunnelStateRepository.on())LocalTunnelService.touch(YouTubeHubActivity.this);else if(!starting&&!permission&&NetworkDiagnostics.physical(YouTubeHubActivity.this)!=null&&SystemClock.elapsedRealtime()-lastRestart>10000){startLocal(false);}}ui.postDelayed(this,2000);}};
 protected void onResume(){super.onResume();if(browserPaused){browserActive=false;browserPaused=false;LocalTunnelService.browser(this,false);connectionLabel();}foreground=true;if(web!=null)web.onResume();if(local&&TunnelStateRepository.on())YouTubeWebRoute.apply(()->{});ui.post(heartbeat);}
 protected void onPause(){if(browserActive)browserPaused=true;foreground=false;ui.removeCallbacks(heartbeat);if(web!=null){web.evaluateJavascript("document.querySelectorAll('video').forEach(v=>v.pause())",null);web.onPause();}if(local&&!permission&&!browserActive)LocalTunnelService.idle(this);super.onPause();}
 protected void onSaveInstanceState(Bundle b){b.putString("url",url);super.onSaveInstanceState(b);}
 void hideFullscreen(){if(fullscreen==null)return;((FrameLayout)getWindow().getDecorView()).removeView(fullscreen);fullscreen=null;if(fullscreenCallback!=null)fullscreenCallback.onCustomViewHidden();fullscreenCallback=null;getWindow().getDecorView().setSystemUiVisibility(0);}
 public void onBackPressed(){if(fullscreen!=null)hideFullscreen();else if(web!=null&&web.canGoBack())web.goBack();else finish();}
 protected void onDestroy(){attempt++;ui.removeCallbacksAndMessages(null);work.shutdownNow();hideFullscreen();if(web!=null){content.removeView(web);web.stopLoading();web.destroy();web=null;}YouTubeWebRoute.release();if(local&&!browserActive)LocalTunnelService.idle(this);super.onDestroy();}
 TextView key(String name,Runnable action){TextView v=new TextView(this);v.setText(name);v.setTextSize(18);v.setGravity(Gravity.CENTER);v.setTextColor(Color.WHITE);v.setBackground(shape(0xffbd3046));v.setContentDescription(name);v.setOnClickListener(w->action.run());return v;}
 GradientDrawable shape(int color){GradientDrawable d=new GradientDrawable();d.setColor(color);d.setCornerRadius(dp(14));return d;}int dp(int n){return Math.round(n*getResources().getDisplayMetrics().density);}
}
