package chat.oldy;
import android.content.*;import android.os.*;import android.widget.*;import org.json.*;import java.util.*;

/** Two cryptographic identities in a disposable local account. No live deletion. */
public class ConversationFeaturesInstrumentation extends Release066Instrumentation {
 public void onStart(){Bundle result=new Bundle();try{
  Context c=getTargetContext();I18n.init(c);new Api(c).configure("https://127.0.0.1:9",new String(new char[64]).replace('\0','0'));Vault v=ChatService.vault(c);JSONObject self=v.identity();v.account(new JSONObject().put("token","offline-fixture-only").put("user",new JSONObject().put("nick","alice").put("name","Алиса").put("enc",self.getString("enc")).put("sig",self.getString("sig")).put("accepted_policy","fixture")));JSONObject bob=v.peer("bobby");if(bob==null)bob=Crypto.identity().put("nick","bobby").put("name","Борис");bob.put("protocol",5);v.pin(bob);
  String original=v.queuePayload("bobby",new JSONObject().put("kind","text").put("text","Сообщение для напоминания"),null);String config=UUID.randomUUID().toString();JSONObject rule=new JSONObject().put("kind","control").put("op","expire_config").put("mid",original).put("event","read").put("config",config);v.queuePayload("bobby",rule,null);
  boolean rejected=false;try{v.applyControl("bobby","bobby",rule,System.currentTimeMillis()+1);}catch(SecurityException expected){rejected=true;}check(rejected,"Recipient changed author's deletion rule");
  JSONObject receipt=new JSONObject().put("kind","control").put("op","expire_event").put("mid",original).put("event","read").put("config",UUID.randomUUID().toString());v.applyControl("bobby","bobby",receipt,System.currentTimeMillis());check(!v.bucket("event_deletions").has(original),"Stale receipt can delete a new configuration");
  receipt.put("config",config);rejected=false;try{v.applyControl("bobby","mallory",receipt,System.currentTimeMillis());}catch(SecurityException expected){rejected=true;}check(rejected,"Unrelated peer could trigger deletion");v.applyControl("bobby","bobby",receipt,System.currentTimeMillis());check(v.bucket("event_deletions").has(original)&&v.has(original),"Deleted before server confirmation");
  rule.put("event","").put("config",UUID.randomUUID().toString());v.queuePayload("bobby",rule,null);check(!v.bucket("event_deletions").has(original)&&v.has(original),"Disabling deletion failed");
  rule.put("event","reply").put("config",UUID.randomUUID().toString());v.queuePayload("bobby",rule,null);JSONObject reply=new JSONObject().put("kind","text").put("text","Ответ без звука").put("silent",true).put("reply",new JSONObject().put("id",original));String incoming=UUID.randomUUID().toString();JSONObject envelope=new JSONObject().put("id",incoming).put("from","bobby").put("to","alice").put("time",System.currentTimeMillis());v.receiveDecoded(envelope,bob,reply);check(v.bucket("event_deletions").has(original)&&v.message(incoming).optBoolean("silent"),"Reply event or silent metadata lost");rule.put("event","").put("config",UUID.randomUUID().toString());v.queuePayload("bobby",rule,null);
  JSONObject watch=YouTubeTogether.invitation("jNQXAC9IVRw");check(YouTubeTogether.valid(watch.getJSONObject("watch")),"Invalid watch invitation");String invitation=v.queuePayload("bobby",watch,null);check(v.message(invitation).has("watch"),"Watch invitation metadata lost");YouTubeTogether.Session session=new YouTubeTogether.Session(null,v,"bobby",watch.getJSONObject("watch"),true);JSONObject state=new JSONObject().put("op","youtube_watch").put("sid",watch.getJSONObject("watch").getString("id")).put("video","jNQXAC9IVRw");check(session.accepts("bobby",state)&&!session.accepts("mallory",state),"Watch peer validation failed");state.put("room",UUID.randomUUID().toString());check(!session.accepts("bobby",state),"Room signal entered a private watch session");state.remove("room");state.put("sid",UUID.randomUUID().toString());check(!session.accepts("bobby",state),"Different invitation controlled player");check(!session.hasPartner(),"Offline guest was treated as connected");session.receive(new JSONObject().put("action","ready").put("seq",1));check(session.hasPartner(),"Joined guest did not activate synchronization");session.lastReceived=SystemClock.elapsedRealtime()-16000;check(!session.hasPartner(),"Disconnected guest kept receiving synchronization");
  JSONObject mini=new JSONObject().put("id",UUID.randomUUID().toString()).put("type","poll").put("title","Куда пойдём?").put("items",new JSONArray().put("Парк").put("Кино"));String poll=v.queuePayload("bobby",new JSONObject().put("kind","text").put("text","Куда пойдём? Парк / Кино").put("mini",mini),null);v.queuePayload("bobby",new JSONObject().put("kind","text").put("text","Голос: Парк").put("mini_update",new JSONObject().put("id",mini.getString("id")).put("type","poll").put("choice",0)),null);
  MainActivity a=(MainActivity)launch(new Intent(c,MainActivity.class).addFlags(Intent.FLAG_ACTIVITY_NEW_TASK),MainActivity.class);long readyUntil=SystemClock.elapsedRealtime()+15000;boolean[] ready={false};while(!ready[0]&&SystemClock.elapsedRealtime()<readyUntil){runOnMainSync(()->ready[0]=a.screen.equals("chats"));Thread.sleep(100);}check(ready[0],"Main screen did not leave splash");runOnMainSync(()->a.openChat("bobby"));JSONObject one=v.message(original),two=v.message(incoming);runOnMainSync(()->{MessageSelection.show(a,one);MessageSelection.show(a,two);check(MessageSelection.selected(a).size()==2,"Multiple message selection failed");check(contains(a.selectionBar,"Выбрано 2"),"Selection count missing");});shot("067-selected-fragment");runOnMainSync(()->{MessageSelection.clear(a);check(contains(a.root,"▶ Смотреть вместе"),"Watch invitation has no join action");check(contains(a.root,"Парк · 1"),"Shared poll did not render its vote");a.messageMenu(one);check(contains(a.activeSheet.getWindow().getDecorView(),"Удаление по событию"),"Event expiry action missing");a.activeSheet.dismiss();});
  check(v.has(original)&&v.has(incoming)&&v.has(poll),"Feature checks damaged local messages");result.putString("stream","OLDI_CONVERSATION_PASS: multi-selection; quiet metadata; encrypted poll and watch invitations; expiry author/peer/config validation; no deletion before server confirmation\n");finish(-1,result);
 }catch(Throwable e){result.putString("stream","OLDI_CONVERSATION_FAIL: "+android.util.Log.getStackTraceString(e));finish(0,result);}}
}
