package chat.oldy;
import android.app.*;import android.content.*;import android.graphics.*;import android.os.*;import android.view.*;import android.widget.*;import org.json.*;import java.io.*;

/** Local emulator fixtures only. Never registers an account or contacts production. */
public class Release066Instrumentation extends Instrumentation {
 public void onCreate(Bundle args){start();}
 public void runOnMainSync(Runnable action){java.util.concurrent.atomic.AtomicReference<Throwable> failure=new java.util.concurrent.atomic.AtomicReference<>();super.runOnMainSync(()->{try{action.run();}catch(Throwable error){failure.set(error);}});if(failure.get()!=null)throw new RuntimeException("Android UI assertion failed",failure.get());}

 volatile Activity resumed;
 public void callActivityOnResume(Activity a){super.callActivityOnResume(a);resumed=a;}
 void mark(String step){Bundle b=new Bundle();b.putString("stream","OLDI_066_STEP: "+step+"\n");sendStatus(1,b);}
 // CI's launcher can ANR while booting. Dismiss only that named system app;
 // never dismiss or suppress an Oldi crash/ANR.
 void dismissLauncherAnr()throws Exception{android.view.accessibility.AccessibilityNodeInfo root=getUiAutomation().getRootInActiveWindow();if(root==null||root.findAccessibilityNodeInfosByText("Quickstep isn't responding").isEmpty())return;for(android.view.accessibility.AccessibilityNodeInfo button:root.findAccessibilityNodeInfosByText("Close app")){if(button.performAction(android.view.accessibility.AccessibilityNodeInfo.ACTION_CLICK)){mark("dismissed-emulator-launcher-anr");Thread.sleep(500);return;}}}
 Activity launch(Intent intent,Class<?> kind)throws Exception{dismissLauncherAnr();resumed=null;runOnMainSync(()->getTargetContext().startActivity(intent));long until=SystemClock.elapsedRealtime()+15000;while(SystemClock.elapsedRealtime()<until){Activity a=resumed;if(a!=null&&kind.isInstance(a))return a;Thread.sleep(80);}throw new AssertionError("Activity did not resume: "+kind.getSimpleName());}
 void check(boolean condition,String message){if(!condition)throw new AssertionError(message);}
 boolean contains(View view,String text){if(view instanceof TextView&&((TextView)view).getText().toString().contains(text))return true;if(view instanceof ViewGroup)for(int i=0;i<((ViewGroup)view).getChildCount();i++)if(contains(((ViewGroup)view).getChildAt(i),text))return true;return false;}
 TextView findText(View v,String text){if(v instanceof TextView&&((TextView)v).getText().toString().equals(text))return (TextView)v;if(v instanceof ViewGroup)for(int i=0;i<((ViewGroup)v).getChildCount();i++){TextView found=findText(((ViewGroup)v).getChildAt(i),text);if(found!=null)return found;}return null;}
 void visible(View root,String text){TextView v=findText(root,text);Rect bounds=new Rect();check(v!=null&&v.getGlobalVisibleRect(bounds)&&bounds.height()>0,"Menu item not visible: "+text);View current=v;while(current!=null){check(current.getAlpha()>.95f,"Menu ancestor transparent: "+text);android.view.ViewParent parent=current.getParent();current=parent instanceof View?(View)parent:null;}}
 void shot(String name)throws Exception{mark(name);runOnMainSync(()->{});Thread.sleep(1800);Bitmap image=getUiAutomation().takeScreenshot();File folder=new File(getTargetContext().getExternalFilesDir(null),"review");folder.mkdirs();try(FileOutputStream out=new FileOutputStream(new File(folder,name+".png"))){image.compress(Bitmap.CompressFormat.PNG,100,out);}image.recycle();}
 public void onStart(){Bundle result=new Bundle();try{
  mark("local-fixture");Context c=getTargetContext();I18n.init(c);new Api(c).configure("https://127.0.0.1:9",new String(new char[64]).replace('\0','0'));
  Vault vault=ChatService.vault(c);JSONObject identity=vault.identity();JSONObject user=new JSONObject().put("nick","alice").put("name","Алиса").put("enc",identity.getString("enc")).put("sig",identity.getString("sig")).put("accepted_policy","fixture");vault.account(new JSONObject().put("user",user).put("token","offline-fixture-only"));JSONObject bob=Crypto.identity().put("nick","bobby").put("name","Борис");vault.pin(bob);vault.queue("bobby","Проверяем новый чат и стикеры");
  mark("launch-main");MainActivity activity=(MainActivity)launch(new Intent(c,MainActivity.class).addFlags(Intent.FLAG_ACTIVITY_NEW_TASK),MainActivity.class);long mainUntil=SystemClock.elapsedRealtime()+15000;boolean[] mainReady={false};while(!mainReady[0]&&SystemClock.elapsedRealtime()<mainUntil){runOnMainSync(()->mainReady[0]=activity.screen.equals("chats"));Thread.sleep(100);}check(mainReady[0],"Main screen stayed on splash");
  for(String theme:new String[]{"light","dark","cyber"}){runOnMainSync(()->{Notices.prefs(c).edit().putString("theme",theme).putBoolean("animations",true).commit();activity.chats();});shot("066-main-"+theme);runOnMainSync(()->{View bar=activity.root.findViewWithTag("primary-navigation");check(bar!=null&&bar.getHeight()>=activity.dp(70),"Navigation too small");});}
  runOnMainSync(activity::profileMenu);shot("066-menu");runOnMainSync(()->{View menu=activity.activeSheet.getWindow().getDecorView();visible(menu,"YouTube");visible(menu,"Видеосвязь");check(!contains(menu,"Возможности"),"Removed services entry remains");check(contains(menu,"Чаты")&&contains(menu,"Контакты")&&contains(menu,"Моё")&&contains(menu,"Настройки"),"Main menu lost primary destinations");check(!contains(menu,"Все возможности")&&!contains(menu,"Мой профиль")&&!contains(menu,"Архив"),"Main menu retains duplicates");activity.activeSheet.dismiss();activity.openChat("bobby");EmojiTray.show(activity);});shot("066-emoji");runOnMainSync(()->{check(contains(activity.emojiPanel,"Стикеры"),"Sticker tab is not visible");check(!contains(activity.emojiPanel,"Живые"),"Old animation picker remains");EmojiTray.fill(activity,5);});shot("066-sticker-panel");runOnMainSync(()->{check(contains(activity.emojiPanel,"Создать из фото")&&contains(activity.emojiPanel,"Создать по описанию"),"Sticker creation modes missing");});
  mark("my-sticker-entry-points");runOnMainSync(()->SettingsHome.own(activity));shot("067-my");runOnMainSync(()->{check(!contains(activity.root,"Все возможности"),"Redundant All features entry remains in My");check(contains(activity.root,"Создать стикер из фото")&&contains(activity.root,"Создать стикер по описанию"),"My lacks direct sticker creation");activity.openChat("bobby");activity.attachments();});Thread.sleep(500);
  boolean modesVisible=false;long dialogUntil=SystemClock.elapsedRealtime()+10000;while(SystemClock.elapsedRealtime()<dialogUntil){dismissLauncherAnr();android.view.accessibility.AccessibilityNodeInfo dialog=getUiAutomation().getRootInActiveWindow();modesVisible=dialog!=null&&!dialog.findAccessibilityNodeInfosByText("Создать стикер из фото").isEmpty()&&!dialog.findAccessibilityNodeInfosByText("Создать стикер по описанию").isEmpty();if(modesVisible)break;Thread.sleep(200);}shot("067-chat-plus");check(modesVisible,"Chat plus menu lacks sticker creation modes");getUiAutomation().performGlobalAction(android.accessibilityservice.AccessibilityService.GLOBAL_ACTION_BACK);
  runOnMainSync(()->NavigationPages.services(activity));shot("067-services");runOnMainSync(()->{check(contains(activity.root,"Создать канал")&&contains(activity.root,"Капсула дня")&&!contains(activity.root,"Опрос")&&!contains(activity.root,"Таймер"),"Removed tools remain");SettingsHome.show(activity);});shot("067-settings-clean");runOnMainSync(()->{check(!contains(activity.root,"Просмотр YouTube")&&!contains(activity.root,"Мои стикеры")&&!contains(activity.root,"Приложения и игры")&&!contains(activity.root,"Архив")&&!contains(activity.root,"Мой профиль"),"Settings retains feature duplicates");});
  runOnMainSync(()->{VideoCalls.show(activity);check(contains(activity.root,"⌂  Главная"),"Video calls have no main-screen return");check(contains(activity.root,"Из чатов")&&contains(activity.root,"Все контакты"),"Call participant sources missing");findText(activity.root,"⌂  Главная").performClick();check(activity.screen.equals("chats"),"Main-screen return did not open chats");activity.openChat("bobby");check((activity.compose.getInputType()&android.text.InputType.TYPE_TEXT_FLAG_AUTO_CORRECT)!=0,"Autocorrection disabled");});
  String editableId=vault.queuePayload("bobby",new JSONObject().put("kind","text").put("text","Текст до правки"),null);JSONObject editable=vault.message(editableId);
  runOnMainSync(()->{activity.openChat("bobby");activity.compose.setText("Незавершённый черновик");activity.messageMenu(editable);check(contains(activity.activeSheet.getWindow().getDecorView(),"Редактировать"),"Own message has no edit action");activity.activeSheet.dismiss();MessageEdits.show(activity,editable);check(contains(activity.activeSheet.getWindow().getDecorView(),"Сохранить")&&contains(activity.activeSheet.getWindow().getDecorView(),"Отмена"),"Editor lacks save/cancel");});shot("068-edit-message");runOnMainSync(()->{activity.activeSheet.dismiss();check(activity.compose.getText().toString().equals("Незавершённый черновик"),"Editing destroyed composer draft");});
  vault.queuePayload("bobby",MessageEdits.payload(vault.message(editableId),"Текст после правки"),null);runOnMainSync(()->{activity.renderMessages();check(contains(activity.root,"Текст после правки")&&contains(activity.root,"изменено"),"Edited text/marker missing");});
  PersonalNotes.put(vault,new JSONObject().put("id","fixture-note").put("title","Идея").put("body","Запись для проверки сохранения").put("updated",System.currentTimeMillis()));check(PersonalNotes.read(new Vault(c)).length()==1,"Note not persisted in account vault");runOnMainSync(()->PersonalNotes.show(activity));shot("068-notes");runOnMainSync(()->SettingsHome.own(activity));check(contains(activity.root,"Заметки"),"My notes destination missing");
  JSONObject message=vault.copy().getJSONArray("messages").getJSONObject(0);runOnMainSync(()->PersonalReminders.put(activity,message,System.currentTimeMillis()+3600000));check(PersonalReminders.entries(vault).has(message.getString("id")),"Reminder was not persisted");runOnMainSync(()->PersonalReminders.show(activity));shot("067-reminders");
  mark("launch-editor");StickerEditorActivity editor=(StickerEditorActivity)launch(new Intent(c,StickerEditorActivity.class).putExtra("text_mode",true).addFlags(Intent.FLAG_ACTIVITY_NEW_TASK),StickerEditorActivity.class);runOnMainSync(()->{editor.description.setText("Рыжий кот в синей толстовке");check(editor.textMode&&editor.description.getParent()!=null,"Description editor missing");check(!contains(editor.body,"ИИ-сервис")&&!contains(editor.body,"OpenAI"),"Technical copy in creation flow");});shot("066-description-editor");runOnMainSync(editor::finish);
  check(new Vault(c).nick().equals("alice"),"Account lost");check(new Vault(c).copy().getJSONArray("messages").length()>0,"Messages lost");
  result.putString("stream","OLDI_066_UI_PASS: three themes, larger navigation, complete menu, emoji/sticker tabs, description editor, local account persistence\n");finish(-1,result);
 }catch(Throwable error){result.putString("stream","OLDI_066_UI_FAIL: "+android.util.Log.getStackTraceString(error));finish(0,result);}}
}
