package chat.oldy;
import java.io.*;import java.security.MessageDigest;import android.net.Uri;import android.app.*;import android.content.*;import android.os.*;import org.json.*;import org.webrtc.*;import java.util.*;import java.util.concurrent.*;

/** Five independent cryptographic devices exchanging live audio/video; no production accounts. */
public class VideoConferenceInstrumentation extends Release066Instrumentation {
 String pin;public void onCreate(Bundle args){pin=args.getString("pin","");start();}
 interface Condition{boolean value()throws Exception;}
 void until(Condition condition,long timeout,String reason)throws Exception{long deadline=SystemClock.elapsedRealtime()+timeout;while(SystemClock.elapsedRealtime()<deadline){if(condition.value())return;Thread.sleep(300);}throw new AssertionError(reason);}
 double[] stats(ConferenceCall.Session call)throws Exception{double[] values=new double[3];CountDownLatch done=new CountDownLatch(call.invited.size()-1);call.execute(()->{for(ConferenceCall.Session.Link link:call.links.values())link.pc.getStats(report->{synchronized(values){for(RTCStats row:report.getStatsMap().values()){Map<String,Object> m=row.getMembers();if(row.getType().equals("inbound-rtp")&&m.get("framesDecoded") instanceof Number)values[0]+=((Number)m.get("framesDecoded")).doubleValue();if(row.getType().equals("outbound-rtp")&&m.get("framesEncoded") instanceof Number)values[1]+=((Number)m.get("framesEncoded")).doubleValue();if(row.getType().equals("transport")&&"connected".equals(m.get("dtlsState")))values[2]++;}}done.countDown();});});check(done.await(10,TimeUnit.SECONDS),"Four WebRTC links not available");return values;}
 void documents(MainActivity a,Vault v)throws Exception{File source=new File(a.getCacheDir(),"fixture-document.bin");MessageDigest original=MessageDigest.getInstance("SHA-256");try(OutputStream out=new FileOutputStream(source)){byte[] block=new byte[32768];for(int i=0;i<block.length;i++)block[i]=(byte)(i*31);for(int i=0;i<65;i++){out.write(block);original.update(block);}out.write(123);original.update((byte)123);}String expected=Crypto.hex(original.digest());CloudMedia.attachDocument(a,Uri.fromFile(source),"application/octet-stream","fixture-document.bin","video_1","");JSONObject file=null;JSONArray messages=v.copy().getJSONArray("messages");for(int i=0;i<messages.length();i++){JSONObject m=messages.getJSONObject(i);if(m.optString("sha256").equals(expected))file=m;}check(file!=null&&file.optBoolean("document")&&file.optString("blob_format").equals(AttachmentCipher.FORMAT),"Generic file was not queued with encrypted records");CloudMedia.download(a,v,file);MessageDigest actual=MessageDigest.getInstance("SHA-256");long count=0;try(InputStream in=MediaFiles.open(a,v.message(file.getString("id")).getString("local"))){byte[] b=new byte[32768];int n;while((n=in.read(b))!=-1){actual.update(b,0,n);count+=n;}}check(count==source.length()&&expected.equals(Crypto.hex(actual.digest())),"Encrypted file upload/download changed bytes");source.delete();mark("068-file-encrypted-roundtrip-pass");}
 public void onStart(){Bundle result=new Bundle();try{Context c=getTargetContext();Api api=new Api(c);api.configure("https://10.0.2.2:8444",pin);Vault v=ChatService.vault(c);JSONObject identity=v.identity();v.account(FixturesInstrumentation.register(api,new JSONObject().put("nick","alice").put("password","local-video-fixture-only").put("name","Alice").put("enc",identity.getString("enc")).put("sig",identity.getString("sig")),""));MainActivity a=(MainActivity)launch(new Intent(c,MainActivity.class).addFlags(Intent.FLAG_ACTIVITY_NEW_TASK),MainActivity.class);api.call("/test-conference/start",new JSONObject(),"");until(()->{JSONArray peers=api.call("/test-conference/status",null,"").getJSONArray("peers");if(peers.length()!=4)return false;for(int i=0;i<4;i++){JSONObject p=peers.getJSONObject(i);check(p.optString("error").isEmpty(),"Independent peer error: "+p.optString("error"));if(!p.optBoolean("ready"))return false;}return true;},30000,"Video peers did not register");List<String> names=Arrays.asList("video_1","video_2","video_3","video_4");for(String n:names)v.pin(api.call("/user/"+n,null,v.token()));
  documents(a,v);
  runOnMainSync(()->{try{ConferenceCall.dial(a,names);}catch(Exception e){throw new RuntimeException(e);}});until(()->ConferenceCall.current!=null&&ConferenceCall.current.ready,20000,"Camera/microphone did not start");ConferenceCall.Session call=ConferenceCall.current;
  until(()->{JSONArray peers=api.call("/test-conference/status",null,"").getJSONArray("peers");for(int i=0;i<4;i++){JSONObject p=peers.getJSONObject(i);check(p.optString("error").isEmpty(),"Independent peer failed: "+p.optString("error"));JSONObject frames=p.getJSONObject("frames");if(frames.length()!=4)return false;Iterator<String> ids=frames.keys();while(ids.hasNext()){JSONObject f=frames.getJSONObject(ids.next());if(f.optInt("video")<5||f.optInt("audio")<10)return false;}}return true;},150000,"Five-party audio/video did not flow on every mesh link");double[] connected=stats(call);check(connected[0]>20&&connected[1]>20&&connected[2]>=4,"RTP video or DTLS missing: "+Arrays.toString(connected));shot("068-five-party-video");
  runOnMainSync(call::mute);Thread.sleep(400);check(call.muted&&!call.audio.enabled(),"Microphone mute failed");runOnMainSync(call::mute);runOnMainSync(call::camera);Thread.sleep(700);check(call.cameraOff&&!call.video.enabled()&&!call.captureRunning,"Camera did not stop");runOnMainSync(call::camera);Thread.sleep(700);check(!call.cameraOff&&call.video.enabled(),"Camera did not resume");getUiAutomation().performGlobalAction(android.accessibilityservice.AccessibilityService.GLOBAL_ACTION_HOME);Thread.sleep(3000);double[] background=stats(call);check(background[0]>connected[0],"Media stopped in background");runOnMainSync(()->call.end("Test complete",true));until(()->ConferenceCall.current==null,12000,"Conference resources were not released");
  api.call("/test-conference/ring",new JSONObject(),"");until(()->ConferenceCall.current!=null&&ConferenceCall.current.incoming,12000,"Incoming video invitation missing");ConferenceCall.Session incoming=ConferenceCall.current;Thread.sleep(700);check(!incoming.accepted&&!incoming.ready,"Incoming invitation started camera before acceptance");launch(new Intent(c,VideoCallActivity.class).putExtra("cid",incoming.id).putExtra("accept",true).addFlags(Intent.FLAG_ACTIVITY_NEW_TASK),VideoCallActivity.class);until(()->incoming.ready&&incoming.connectedAt>0,30000,"Accepted incoming video did not connect");Thread.sleep(3500);double[] pair=stats(incoming);check(pair[0]>10&&pair[1]>10&&pair[2]>=1,"Two-party media or DTLS missing");runOnMainSync(()->incoming.end("Incoming test complete",true));until(()->ConferenceCall.current==null,12000,"Incoming call resources not released");
  result.putString("stream","OLDI_CONFERENCE_PASS: five independent identities, all 20 directed audio/video flows, DTLS on four Android links, camera/microphone controls, background video and consented two-party incoming video verified\n");finish(-1,result);
 }catch(Throwable e){ConferenceCall.Session call=ConferenceCall.current;if(call!=null)call.end("Test failed",true);result.putString("stream","OLDI_CONFERENCE_FAIL: "+android.util.Log.getStackTraceString(e));finish(0,result);}}
}
